Implement Tour Layout
arsensaliev/demal-android pull request #10
Opened 2021-08-09 19:28 UTC by tpyc12

2021-08-10 06:19 UTC, arsensaliev commented
Нужно удалить папку .idea. Потом запушить изменения.

2021-08-12 06:33 UTC, arsensaliev commented
Надо исправить конфликты, если не знаешь как это делать то напиши Роме он может помочь.

2021-08-18 14:46 UTC, Romeo2005 requested changes
Нужно исправить комменты

2021-08-18 14:46 UTC, RomchaDev commented on app/build.gradle
> +
Нужно брать зависимости из Dependencies

2021-08-18 14:46 UTC, RomchaDev commented on app/src/main/java/com/demal/ViewPagerTourAdapter.kt
> +    }
Изображения нужно брать из репозитория в виде ссылок и это должно происходить во вью модели. Пока репозитория нету, брать оттуда ссылки не получится, но imageLoader уже есть и для загрузки изображений нужно использовать его. А во вью модели пока можно создать заглушку в виде списка ссылок

2021-08-18 14:46 UTC, RomchaDev commented on app/src/main/java/com/demal/ViewPagerTourFragment.kt
> +        )
Уже писал о том, в каком виде должны храниться изображения

2021-08-18 14:46 UTC, RomchaDev commented on app/src/main/java/com/demal/ViewPagerTourFragment.kt
> +
Фрагменты должны наследоваться от BaseFragment

2021-08-18 14:46 UTC, RomchaDev commented on app/src/main/res/layout/item_view_pager.xml
> +
Зачем здесь ConstraintLayout?

2021-08-18 14:46 UTC, Romeo2005 commented on app/src/main/res/layout/fragment_tour_description.xml
> +<?xml version="1.0" encoding="utf-8"?>
Лучше назвать файл fragment_tour. Непонятно при чём тут description

2021-08-18 14:46 UTC, Romeo2005 commented on app/src/main/res/layout/fragment_tour_description.xml
> +            android:id="@+id/close_button"
С Fab какие-то проблемы. Возникает render problem. А ещё он не оч похож на то, что в фигме, но с меня самого дизайнер весьма сомнительный, поэтому спроси у Арсена на щёт этого.

2021-08-18 14:47 UTC, Romeo2005 commented
Нужно вынести свою фичу в отдельный модуль

2021-08-18 17:29 UTC, arsensaliev commented on app/src/main/res/layout/fragment_tour_description.xml
> +            android:id="@+id/close_button"
Посмотрите решение Владимира. Он сделал как просто кнопку MaterialButton.

2021-08-19 14:13 UTC, arsensaliev requested changes

2021-08-19 14:13 UTC, arsensaliev commented on app/src/main/res/layout/fragment_tour_description.xml
> +            android:layout_marginStart="20dp"
Все размеры и отступы лучше писать в dimens

2021-09-08 19:14 UTC, tpyc12 commented on app/build.gradle
> +
fix: перенес зависимость в Dependencies

2021-09-08 19:15 UTC, tpyc12 commented on app/src/main/java/com/demal/ViewPagerTourAdapter.kt
> +    }
fix: перенес во вьюмодель, прошу помочь достать лист картинок.

2021-09-08 19:15 UTC, tpyc12 commented on app/src/main/java/com/demal/ViewPagerTourFragment.kt
> +        )
fix

2021-09-08 19:16 UTC, tpyc12 commented on app/src/main/java/com/demal/ViewPagerTourFragment.kt
> +
fix: унаследовал

2021-09-08 19:16 UTC, tpyc12 commented on app/src/main/res/layout/item_view_pager.xml
> +
Чтобы привязать картинку

2021-09-08 19:17 UTC, tpyc12 commented on app/src/main/res/layout/fragment_tour_description.xml
> +            android:layout_marginStart="20dp"
Fix: вынес

2021-09-14 15:36 UTC, Romeo2005 requested changes
Как-то так

2021-09-14 15:36 UTC, RomchaDev commented on app/src/main/java/com/demal/TourFragment.kt
> +        binding.tourBottomSheet.textViewDescription.text = "Что-то пошло не так"
Нужно вынести в strings.xml

2021-09-14 15:36 UTC, Romeo2005 commented on app/src/main/java/com/demal/TourViewModel.kt
> +        //Надо написать загрузку картинок, не могу, прошу помочь.
Я бы создал класс TourViewState, в котором, помимо всего прочего, находился бы список ссылок на картинки. В методе init, который вызывается из фрагмента, я бы получал из интерактора тур, из которого доставал бы список  ссылок на изображения. Далее этот список должен через TourViewState попасть во фрагмент, а оттуда в адаптер. В адаптер нужно заинджектить imageLoader, а дальше уже всё просто. Хотя, можно обойтись и без TourViewState и вместо него в liveDtata совать сам тур, как сейчас и происходит, но лучше так не делать.

2021-09-14 15:36 UTC, Romeo2005 commented on app/src/main/java/com/demal/TourViewModel.kt
> +    fun likePressed(tour: LikableTour) {
Этот метод не вызывается

2021-09-14 15:36 UTC, Romeo2005 commented on app/src/main/res/layout/item_view_pager.xml
> +
А что мешает использовать FrameLayout?

2021-09-21 17:44 UTC, Romeo2005 requested changes
3 коммента

2021-09-21 17:44 UTC, Romeo2005 commented on app/src/main/java/com/demal/navigation/Navigator.kt
> +    override fun goBack() {
Уже есть метод back()

2021-09-21 17:44 UTC, Romeo2005 commented on feature-tour/src/main/java/com/demal/feature_tour/navigation/TourNavigator.kt
> +    fun goBack()
Уже есть метод back()

2021-09-21 17:44 UTC, Romeo2005 commented on repository/src/main/java/com/demal/repository/repository/ToursRepository.kt
> +    suspend fun getTourById(id: Int): TourResponse
Я бы не выносил из репозитория роботу с response-классами

2021-09-21 19:31 UTC, Romeo2005 approved these changes

2021-09-21 19:31 UTC, merged