Refactor feature-wishlist
arsensaliev/demal-android pull request #14
Opened 2021-08-11 08:39 UTC by Dentag

Moved Wishlist Layout And Resources To feature-wishlist Module

2021-08-12 05:26 UTC, arsensaliev requested changes

2021-08-12 05:26 UTC, arsensaliev commented on feature-wishlist/src/main/res/layout/fragment_wishlist.xml
> -        tools:listitem="@layout/item_tour" />
С какой целью убрали tools:listitem ?

2021-08-12 05:26 UTC, arsensaliev commented on feature-wishlist/src/main/res/values/colors.xml
> +    <color name="black_dark">#CC000000</color>
Этот цвет много где используется. Может его перенести в core модуль и оттуда его переиспользовать в проекте ?

2021-08-12 05:26 UTC, arsensaliev commented on feature-wishlist/src/main/res/values/dimens.xml
> +    <dimen name="margin_standard">20dp</dimen>
стандартные значения надо перенести в core модуль.

2021-08-12 05:26 UTC, arsensaliev commented on feature-wishlist/build.gradle
> +
Надо добавить core модуль для использования базовых стилей и классов. Подключать надо так: 
implementation project(Modules.core)

2021-08-12 05:26 UTC, arsensaliev commented
Конфликты надо исправить. Если не знаете как это делать то спросите Рому.

2021-08-12 07:29 UTC, Dentag commented on feature-wishlist/src/main/res/layout/fragment_wishlist.xml
> -        tools:listitem="@layout/item_tour" />
item_tour находится в другом модуле. Когда определимся с модульной архитектурой - можно будет прицепить к этому модулю тот, в котором находится item_tour и вернуть это поле.

2021-08-12 07:34 UTC, Dentag commented on feature-wishlist/src/main/res/values/dimens.xml
> +    <dimen name="margin_standard">20dp</dimen>
Создам для этого отдельную ветку

2021-08-16 10:21 UTC, Dentag commented on feature-wishlist/src/main/res/layout/fragment_wishlist.xml
> -        tools:listitem="@layout/item_tour" />
fixed

2021-08-16 10:21 UTC, Dentag commented on feature-wishlist/src/main/res/values/colors.xml
> +    <color name="black_dark">#CC000000</color>
fixed

2021-08-16 10:21 UTC, Dentag commented on feature-wishlist/src/main/res/values/dimens.xml
> +    <dimen name="margin_standard">20dp</dimen>
fixed

2021-08-16 10:21 UTC, Dentag commented on feature-wishlist/build.gradle
> +
fixed

2021-08-16 14:32 UTC, arsensaliev approved these changes

2021-08-16 14:32 UTC, merged