Implement feature-onboarding Module
arsensaliev/demal-android pull request #15
Opened 2021-08-12 07:14 UTC by GianaMaria

ViewPager2 реализован через отдельный фрагмент (базовый), чтобы добавить индикатор навигации фрагментов. CircleIndicator3, который будет отображаться поверх указанных трех фрагментов в аррай листе базового фрагмента. В макетах индикатор не отображается, но его стиль указан в базовом (белый цвет)

2021-08-15 18:37 UTC, Romeo2005 requested changes
Всё как всегда. Исправляешь замечание - пишешь Fixed.

2021-08-15 18:37 UTC, RomchaDev commented on feature-onboarding/build.gradle
> +
android {...} не нужен. Oн один для всего приложения и находится в build.gradle уровня проекта.

2021-08-15 18:37 UTC, RomchaDev commented on feature-onboarding/build.gradle
> +}
Зависимости нужно брать из Dependencies

2021-08-15 18:37 UTC, RomchaDev commented on feature-onboarding/src/main/res/font/roboto.xml
> +</font-family>
Шрифты уже есть в core модуле. Их нужно брать оттуда.

2021-08-15 18:37 UTC, RomchaDev commented on feature-onboarding/src/main/res/font/roboto_bold.xml
> +</font-family>
Шрифты уже есть в core модуле. Их нужно брать оттуда.

2021-08-15 18:37 UTC, RomchaDev commented on feature-onboarding/src/main/res/values/colors.xml
> +</resources>
В core модуле есть абсолютно идентичный файл. Нужно использовать его а из своего модуля colors.xml удали.

2021-08-15 18:37 UTC, RomchaDev commented on feature-onboarding/src/main/java/com/demal/feature_onboarding/adapter/ViewPagerAdapter.kt
> +    }
Разве не будет лучше написать when в createFragment() вместо того, чтобы создавать все фрагменты сразу?

2021-08-15 18:37 UTC, Romeo2005 commented on feature-onboarding/src/main/java/com/demal/feature_onboarding/fragments/ViewPagerFragment.kt
> +        inflater: LayoutInflater, container: ViewGroup?,
Лучше назвать фрагмент OnboardingFragment. Его нужно унаследовать от BaseFragment и создать для него view model.

2021-08-15 18:37 UTC, Romeo2005 commented on feature-onboarding/src/main/java/com/demal/feature_onboarding/fragments/WelcomeFragment.kt
> +}
Зачем ты создаёшь 3 разных фрагмента, если можно создать один и передавать ему разный текст и разные отступы в arguments? Это также касается и лаяутов.

2021-08-15 18:37 UTC, Romeo2005 commented on feature-onboarding/src/main/java/com/demal/feature_onboarding/fragments/WelcomeSecondFragment.kt
> +    }
Зачем ты создаёшь 3 разных фрагмента, если можно создать один и передавать ему разный текст и разные отступы в arguments? Это также касается и лаяутов.

2021-08-15 18:37 UTC, Romeo2005 commented on feature-onboarding/src/main/java/com/demal/feature_onboarding/fragments/WelcomeThirdFragment.kt
> +}
Зачем ты создаёшь 3 разных фрагмента, если можно создать один и передавать ему разный текст и разные отступы в arguments? Это также касается и лаяутов.

2021-08-15 18:37 UTC, Romeo2005 commented on feature-onboarding/src/main/res/layout/fragment_view_pager.xml
> +
Назови этот лаяут layout_onboarding и вынеси кнопку "Дальше" в него.

2021-08-15 18:37 UTC, Romeo2005 commented on feature-onboarding/src/main/res/layout/fragment_welcome.xml
> +    tools:context="com.demal.feature_onboarding.fragments.WelcomeFragment">
Не нужно 3 разных лаяута. Уже писал об этом.

2021-08-15 18:37 UTC, Romeo2005 commented on feature-onboarding/src/main/res/layout/fragment_welcome_second.xml
> +
Не нужно 3 разных лаяута. Уже писал об этом.

2021-08-15 18:37 UTC, Romeo2005 commented on feature-onboarding/src/main/res/layout/fragment_welcome_third.xml
> +        android:src="@drawable/ic_vector"
Не нужно 3 разных лаяута. Уже писал об этом.

2021-08-15 18:37 UTC, Romeo2005 commented on feature-onboarding/src/main/res/values/font_certs.xml
> +    </array>
Шрифты нужно брать из core модуля.

2021-08-15 18:37 UTC, Romeo2005 commented on feature-onboarding/src/main/res/values/preloaded_fonts.xml
> +    </array>
Шрифты нужно брать из core модуля.

2021-08-15 18:37 UTC, Romeo2005 commented on app/src/main/AndroidManifest.xml
>      </application>
Шрифты нужно брать из core модуля.

2021-08-15 18:37 UTC, Romeo2005 commented on feature-onboarding/src/main/res/values/styles.xml
> +        <item name="android:textAllCaps">false</item>
ButtonStyle должен от чего-то наследоваться. Можно наследовать Widget.MaterialComponents.Button, но надо будет добавить атрибут textAppearence, для которого придётся создать отдельный стиль. Студия тебе об этом тоже сообщит.

2021-08-15 18:42 UTC, Romeo2005 commented
Сделай merge ветки dev в свою ветку и исправь merge-conflict

2021-09-05 09:23 UTC, GianaMaria commented on feature-onboarding/src/main/res/font/roboto.xml
> +</font-family>
Шрифты берутся из core модуля

2021-09-05 09:23 UTC, GianaMaria commented on feature-onboarding/src/main/res/font/roboto_bold.xml
> +</font-family>
Шрифты берутся из core модуля

2021-09-05 09:24 UTC, GianaMaria commented on feature-onboarding/build.gradle
> +}
fix : Зависимости берутся из Dependencies

2021-09-05 09:25 UTC, GianaMaria commented on feature-onboarding/src/main/res/values/colors.xml
> +</resources>
fix : удалила этот файл и беру из core colors

2021-09-05 09:25 UTC, GianaMaria commented on feature-onboarding/src/main/java/com/demal/feature_onboarding/adapter/ViewPagerAdapter.kt
> +    }
fix : реализация теперь сделана в одном фрагменте с разными данными

2021-09-05 09:26 UTC, GianaMaria commented on feature-onboarding/src/main/java/com/demal/feature_onboarding/fragments/WelcomeFragment.kt
> +}
fix : Теперь один лайаут, остальные удалены

2021-09-05 09:26 UTC, GianaMaria commented on feature-onboarding/src/main/java/com/demal/feature_onboarding/fragments/WelcomeSecondFragment.kt
> +    }
fix : исправлено

2021-09-05 09:26 UTC, GianaMaria commented on feature-onboarding/src/main/java/com/demal/feature_onboarding/fragments/WelcomeThirdFragment.kt
> +}
fix : исправлено

2021-09-05 20:50 UTC, Romeo2005 requested changes
Нужно отвечать на каждый комментарий. Иначе непонятно, что нужно проверять, а что нет

2021-09-05 20:50 UTC, Romeo2005 commented on feature-onboarding/src/androidTest/java/com/demal/feature_onboarding/ExampleInstrumentedTest.kt
> +
![Screenshot from 2021-09-05 23-20-33](https://user-images.githubusercontent.com/67197145/132140425-10acf163-bf58-4413-8de5-461115009a9b.png)

2021-09-05 20:50 UTC, Romeo2005 commented on feature-onboarding/src/main/java/com/demal/feature_onboarding/fragments/WelcomeFragment.kt
> +    private val binding = _binding!!
Тут будет NPE, так как после присвоения _binding null, ты делаешь _binding!!. Нужно тестировать свой код.

2021-09-05 20:50 UTC, Romeo2005 commented on feature-onboarding/src/main/java/com/demal/feature_onboarding/adapter/ViewPagerAdapter.kt
> +        private const val POSITION_THREE = 3
Эти константы должны быть общими для фрагмента и адаптера.

2021-09-05 20:50 UTC, Romeo2005 commented on feature-onboarding/src/main/java/com/demal/feature_onboarding/fragments/WelcomeFragment.kt
> +        private const val POSITION_THREE = 3
Эти константы должны быть общими для фрагмента и адаптера.

2021-09-05 20:50 UTC, Romeo2005 commented on feature-onboarding/src/main/java/com/demal/feature_onboarding/fragments/ViewPagerFragment.kt
> +class ViewPagerFragment : Fragment() {
Название слишком общее. Назови его OnboardingFragment.

2021-09-05 20:50 UTC, Romeo2005 commented on feature-onboarding/src/main/java/com/demal/feature_onboarding/fragments/WelcomeFragment.kt
> +        binding.buttonWelcome.text = resources.getString(R.string.welcomeButton)
Где на неё слушатель вешается?

2021-09-05 20:50 UTC, Romeo2005 commented on feature-onboarding/src/main/res/layout/fragment_welcome.xml
> +    <com.google.android.material.button.MaterialButton
Я бы её вынес туда, где сейчас находится circleIndicator и через адаптер управлял бы viewpager.

2021-09-25 16:10 UTC, merged