Implement Profile Edit
arsensaliev/demal-android pull request #18
Opened 2021-08-12 18:36 UTC by BikerIndian

2021-08-14 10:33 UTC, arsensaliev approved these changes
Ваш верстка выглядит плохо, сделайте так как в figma. После того как это сделаете исправьте конфликты.

2021-08-14 10:44 UTC, arsensaliev requested changes
![Profile Edit (1)](https://user-images.githubusercontent.com/52528182/129443840-9275fe5d-5165-4b33-812d-35f281e927be.png)
![image](https://user-images.githubusercontent.com/52528182/129443852-8f9d56e7-4773-43f3-b0a0-5a50925f4f7d.png)

То что вы сделали похоже на итоговую ?

2021-08-18 10:41 UTC, arsensaliev requested changes

2021-08-18 10:41 UTC, arsensaliev commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +                tools:ignore="UseAppTint" />
Нельзя игнорить ошибки.

2021-08-18 10:41 UTC, arsensaliev commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +            tools:ignore="MissingConstraints">
Нельзя игнорить ошибки!

2021-08-18 10:41 UTC, arsensaliev commented on feature-profile-edit/src/main/res/values/themes.xml
> +        <item name="android:textSize">14dp</item>
Размер текста надо указывать в sp !

2021-08-18 10:41 UTC, arsensaliev commented on feature-profile-edit/src/main/res/values/themes.xml
> +        <item name="android:textSize">15dp</item>
Размер текста надо указывать в sp !

2021-08-18 10:41 UTC, arsensaliev commented on feature-profile-edit/src/main/res/values/strings.xml
> +    <string name="profile_edit_surname">Фамилия</string>
Лучше использовать слова firstName и lastName .

2021-08-18 10:41 UTC, arsensaliev commented on feature-profile-edit/src/main/res/values/strings.xml
> +    <string name="profile_edit_surname_err">Заполните фамилию</string>
Лучше использовать слова firstName и lastName .

2021-08-18 10:41 UTC, arsensaliev commented
Нужно исправить конфликты!

2021-08-18 11:34 UTC, arsensaliev requested changes
Контент должен быть ровно по центру экрана. Она сейчас выше чем надо. Также почему аватарка в отдельном CardView ? Надо было весь контент в один контейнер засунуть.
![image](https://user-images.githubusercontent.com/52528182/129890929-18f615d5-7165-4efb-a7c9-99db95348a2a.png)

2021-08-18 11:34 UTC, arsensaliev commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +            android:layout_marginEnd="20dp"
Размеры укажи в dimens в своем модуле.

2021-08-18 11:34 UTC, arsensaliev commented on feature-profile-edit/src/main/res/values/themes.xml
> +        <item name="android:backgroundTint">#6550EE</item>
цвета надо брать с colors ресурса

2021-08-18 11:34 UTC, arsensaliev commented on feature-profile-edit/src/main/res/values/themes.xml
> +        <item name="boxStrokeColor">#6200EE</item>
цвета надо брать с colors ресурса

2021-08-18 11:34 UTC, arsensaliev commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +                android:tint="#80000000"
цвета надо брать с colors ресурса и указывать в themes лучше указывать стили.

2021-08-18 11:34 UTC, arsensaliev commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +                tools:ignore="UseAppTint" />
Также если не получается сделать затемнение фото, я могу подсказать один метод. 
Просто засуньте ImageView во FrameLayout. И выставьте FrameLayout:
android:foreground="#80000000"

2021-08-18 11:34 UTC, arsensaliev commented on feature-profile-edit/src/main/res/values/themes.xml
> +        <item name="boxStrokeColor">#6200EE</item>
Кстати это неправильный цвет. Должен быть как в core модуле. color/purple_light

2021-08-18 11:43 UTC, arsensaliev requested changes

2021-08-18 11:43 UTC, arsensaliev commented on feature-profile-edit/src/main/res/drawable/ic_camera.xml
> +<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
Зачем этот файл ? Думаю этот файл бесполезный, так как можно сразу указать на @drawble/ic_bx_camera.

2021-08-18 17:27 UTC, arsensaliev requested changes

2021-08-18 17:27 UTC, arsensaliev commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/view/ProfileEditFragment.kt
> +class ProfileEditFragment : Fragment(R.layout.fragment_profile_edit)
Надо наследоваться от BaseFragment

2021-08-19 07:27 UTC, BikerIndian commented on feature-profile-edit/src/main/res/values/strings.xml
> +    <string name="profile_edit_surname_err">Заполните фамилию</string>
Сделано

2021-08-19 07:57 UTC, BikerIndian commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +            tools:ignore="MissingConstraints">
При отключении ошибок Android Studio думает, что
В TextInputLayout не указаны размеры, хотя эти размеры указаны в стилях.
Я отключаю игнорирование ошибок ошибок и дублирую размеры во всех TextInputLayout?

2021-08-20 04:23 UTC, arsensaliev commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +            tools:ignore="MissingConstraints">
Не знаю как это сделать, как но уберите всё равно уберите игнорирование ошибки!

2021-08-20 04:25 UTC, arsensaliev commented on feature-profile-edit/src/main/res/values/strings.xml
> +    <string name="profile_edit_surname_err">Заполните фамилию</string>
Нет, не сделано, вы не переименовали surname на lastName.

2021-08-20 04:28 UTC, arsensaliev commented on feature-profile-edit/src/main/res/drawable/ic_camera.xml
> +<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
Зачем без разрешения нажали на кнопку Resolve conversation ?

2021-08-20 04:58 UTC, arsensaliev requested changes
Исправьте конфликты.

2021-08-20 04:58 UTC, arsensaliev commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/view/ProfileEditFragment.kt
> +        val сityMessageError = resources.getString(R.string.profile_edit_сity_err)
Мы решили в проекте использовать ViewBinding, уберите весь этот код.

2021-08-20 04:58 UTC, arsensaliev commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/view/ProfileEditFragment.kt
> +class ProfileEditFragment : Fragment(R.layout.fragment_profile_edit) {
Надо наследоваться от BaseFragment в core модуле

2021-08-20 04:58 UTC, arsensaliev commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/view/ProfileEditFragment.kt
> +    private val EMPTY_STRING = ""
Зачем нужна эта переменная ?

2021-08-20 04:58 UTC, arsensaliev commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/view/ProfileEditFragment.kt
> +    private fun setEditorListener(editFirstNameLayout: TextInputLayout, editFirstName: TextInputEditText, firstNameMessageError: String) {
В параметрах указан editFirstName но вы в других местах передаёте country и city и surName. Тогда стоит переименовать параметр на просто inputLayout.

2021-08-20 04:58 UTC, arsensaliev commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/view/ProfileEditFragment.kt
> +    private fun checkErrors(inputLayout: TextInputLayout, editText: TextInputEditText, firstNameMessageError: String): Boolean {
Причем тут параметр firstNameMessageError ? Она же не отображает ошибку только для имени! По коду видно что это универсальный метод отображение ошибок. Стоит переименовать на errorMessage!

2021-08-20 04:58 UTC, arsensaliev commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/view/ProfileEditFragment.kt
> +        return if (shouldShowError(editText)) {
Так лучше не возвращать значения. Такой стиль возврата значения путает разработчика. Напишите обычный стиль if else и внутри каждого возвращайте значение

2021-08-20 04:58 UTC, arsensaliev commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/view/ProfileEditFragment.kt
> +    private fun showErrorOn(editText: TextInputLayout, errText: String) {
В некоторых местах у вас inputLayout, здесь почему то editText. Может выберите одно ? Например inputLayout.

2021-08-20 04:58 UTC, arsensaliev commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/view/ProfileEditFragment.kt
> +    private fun showErrorOn(editText: TextInputLayout, errText: String) {
Также не стоит звать параметры коротки названиями. Назови его более понятным, например errorMessage.

2021-08-20 04:58 UTC, arsensaliev commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/view/ProfileEditFragment.kt
> +    private fun showErrorOff(editText: TextInputLayout) {
В некоторых местах у вас inputLayout, здесь почему то editText. Может выберите одно ? Например inputLayout.

2021-08-20 04:58 UTC, arsensaliev commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/view/ProfileEditFragment.kt
> +            val textLength = editText.text!!.length
Перед return лучше оставлять отступ.

2021-08-20 04:58 UTC, arsensaliev commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/view/ProfileEditFragment.kt
> +        return false
Перед return лучше оставлять отступ.

2021-08-20 04:58 UTC, arsensaliev commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/view/ProfileEditFragment.kt
> +
Удалите лишние отступы.

2021-08-20 04:58 UTC, arsensaliev commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +        android:layout_height="match_parent"
Студия показывает здесь предупреждение. Все предупреждения стоит исправить!

2021-08-20 04:58 UTC, arsensaliev commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +    <ScrollView
Добавьте отступ перед каждый новым view

2021-08-20 04:58 UTC, arsensaliev commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +    <androidx.constraintlayout.widget.ConstraintLayout
Добавьте отступ перед каждый новым view

2021-08-20 04:58 UTC, arsensaliev commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +
Здесь слишком много отступов. Хватит и одного

2021-08-20 04:58 UTC, arsensaliev commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +            android:layout_marginStart="20dp"
Все размеры надо указывать в dimens!

2021-08-20 04:58 UTC, arsensaliev commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +                </com.google.android.material.textfield.TextInputLayout>
Добавьте отступ перед закрывающим TextInputLayout.

2021-08-20 04:58 UTC, arsensaliev commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +                    android:layout_marginTop="86dp"
Размеры в dimens

2021-08-20 04:58 UTC, arsensaliev commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +                </com.google.android.material.textfield.TextInputLayout>
Добавьте отступ перед закрывающим TextInputLayout.

2021-08-20 04:58 UTC, arsensaliev commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +                </com.google.android.material.textfield.TextInputLayout>
Добавьте отступ перед закрывающим TextInputLayout.

2021-08-20 04:58 UTC, arsensaliev commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +                </com.google.android.material.textfield.TextInputLayout>
Добавьте отступ перед закрывающим TextInputLayout.

2021-08-20 04:58 UTC, arsensaliev commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +                    app:hintAnimationEnabled="false"
Зачем вы эту опцию добавили ? Почему она нет в остальных ?

2021-08-20 04:58 UTC, arsensaliev commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +                    android:layout_marginBottom="20dp"
В dimens укажите размеры

2021-08-20 04:58 UTC, arsensaliev commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +
Здесь 2 отступа. Хватит и одного.

2021-08-20 04:58 UTC, arsensaliev commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +        <androidx.cardview.widget.CardView
Я говорил чтобы всё это было в одном контейнере. Так как в дизайне видно что всё находится в одном контейнере. 
![image](https://user-images.githubusercontent.com/52528182/130180828-9df1384c-cdb2-493b-acc4-8c04c43939f0.png)

2021-08-20 04:58 UTC, arsensaliev commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +
Уберите лишний отступ.

2021-08-20 04:58 UTC, arsensaliev commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +                android:layout_width="91dp"
в dimens значение поставьте.

2021-08-20 04:58 UTC, arsensaliev commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +
Излишние отступы.

2021-08-20 04:58 UTC, arsensaliev commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +
Излишние отступы.

2021-08-20 04:58 UTC, arsensaliev commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +    </ScrollView>
Добавьте 1 отступ перед каждым новым view.

2021-08-20 04:58 UTC, arsensaliev commented on feature-profile-edit/src/main/res/values/strings.xml
> +    <string name="profile_firstName_name">Имя</string>
Почему слово name повторяется ? profile_first_name можете назвать.

2021-08-20 04:58 UTC, arsensaliev commented on feature-profile-edit/src/main/res/values/strings.xml
> +    <string name="profile_edit_surname">Фамилия</string>
Лучше вместо surname использовать profile_lastName. Также почему здесь есть слово edit, а в firstname нет ?

2021-08-20 04:58 UTC, arsensaliev commented on feature-profile-edit/src/main/res/values/themes.xml
> +
излишний отступ. Также все размеры которые здесь укажите в dimens.

2021-08-20 06:54 UTC, BikerIndian commented on feature-profile-edit/src/main/res/values/strings.xml
> +    <string name="profile_edit_surname_err">Заполните фамилию</string>
переименовал в  last_name

2021-08-20 13:36 UTC, BikerIndian commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/view/ProfileEditFragment.kt
> +    private val EMPTY_STRING = ""
Потому что в коде не должно быть текст указан в явном виде. Поменял на null как показано в material.io

2021-08-23 12:21 UTC, BikerIndian commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +            tools:ignore="MissingConstraints">
Исправил

2021-08-23 12:21 UTC, BikerIndian commented on feature-profile-edit/src/main/res/values/themes.xml
> +        <item name="android:textSize">14dp</item>
Исправил

2021-08-23 12:21 UTC, BikerIndian commented on feature-profile-edit/src/main/res/values/themes.xml
> +        <item name="android:textSize">15dp</item>
Исправил

2021-08-23 12:21 UTC, BikerIndian commented on feature-profile-edit/src/main/res/values/strings.xml
> +    <string name="profile_edit_surname">Фамилия</string>
Исправил

2021-08-23 12:22 UTC, BikerIndian commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +            android:layout_marginEnd="20dp"
перенес

2021-08-23 12:22 UTC, BikerIndian commented on feature-profile-edit/src/main/res/values/themes.xml
> +        <item name="android:backgroundTint">#6550EE</item>
перенес

2021-08-23 12:22 UTC, BikerIndian commented on feature-profile-edit/src/main/res/values/themes.xml
> +        <item name="boxStrokeColor">#6200EE</item>
сделано

2021-08-23 12:23 UTC, BikerIndian commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +                android:tint="#80000000"
перенес в color

2021-08-23 12:24 UTC, BikerIndian commented on feature-profile-edit/src/main/res/drawable/ic_camera.xml
> +<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
файл убрал

2021-08-23 12:24 UTC, BikerIndian commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/view/ProfileEditFragment.kt
> +class ProfileEditFragment : Fragment(R.layout.fragment_profile_edit)
добавил наследование

2021-08-23 12:25 UTC, BikerIndian commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/view/ProfileEditFragment.kt
> +        val сityMessageError = resources.getString(R.string.profile_edit_сity_err)
добавил Binding

2021-08-23 12:25 UTC, BikerIndian commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/view/ProfileEditFragment.kt
> +class ProfileEditFragment : Fragment(R.layout.fragment_profile_edit) {
добавил наследование

2021-08-23 12:26 UTC, BikerIndian commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/view/ProfileEditFragment.kt
> +    private fun setEditorListener(editFirstNameLayout: TextInputLayout, editFirstName: TextInputEditText, firstNameMessageError: String) {
переименовал

2021-08-23 12:26 UTC, BikerIndian commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/view/ProfileEditFragment.kt
> +    private fun checkErrors(inputLayout: TextInputLayout, editText: TextInputEditText, firstNameMessageError: String): Boolean {
переименовал

2021-08-23 12:26 UTC, BikerIndian commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +
убрал

2021-08-23 12:26 UTC, BikerIndian commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +    </ScrollView>
сделано

2021-08-23 12:27 UTC, BikerIndian commented on feature-profile-edit/src/main/res/values/strings.xml
> +    <string name="profile_firstName_name">Имя</string>
убрал

2021-08-23 12:29 UTC, BikerIndian commented on feature-profile-edit/src/main/res/values/themes.xml
> +
отступы убрал

2021-08-23 12:49 UTC, Romeo2005 commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +            tools:ignore="MissingConstraints">
Все ошибки, кроме Content labels missing нужно исправить. Touch size too small говорит о том, что нужно увеличить размер editText. TextAppearence мы уже обсуждали

2021-08-23 13:16 UTC, Romeo2005 commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/view/ProfileEditFragment.kt
> +        val сityMessageError = resources.getString(R.string.profile_edit_сity_err)
bindingNullable для других целей создан. Используй binding

2021-08-24 05:46 UTC, BikerIndian commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +                tools:ignore="UseAppTint" />
затемнение фото работает, засовывать ImageView во FrameLayout?

2021-08-24 05:47 UTC, BikerIndian commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/view/ProfileEditFragment.kt
> +        val сityMessageError = resources.getString(R.string.profile_edit_сity_err)
сделал

2021-08-24 10:05 UTC, BikerIndian commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +            tools:ignore="MissingConstraints">
Нужно поставить в студии Settings > Experimental > [x] Use new Layout Rendering Engine

2021-08-26 12:19 UTC, BikerIndian commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/view/ProfileEditFragment.kt
> +    private fun showErrorOn(editText: TextInputLayout, errText: String) {
проверка будет из библиотеки

2021-08-26 12:20 UTC, BikerIndian commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +        android:layout_height="match_parent"
исправлено

2021-08-26 12:20 UTC, BikerIndian commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/view/ProfileEditFragment.kt
> +
убрал

2021-08-26 12:21 UTC, BikerIndian commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +    <ScrollView
добавил

2021-08-26 12:21 UTC, BikerIndian commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +    <androidx.constraintlayout.widget.ConstraintLayout
добавил

2021-08-26 12:23 UTC, BikerIndian commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +            android:layout_marginStart="20dp"
указал

2021-08-26 12:23 UTC, BikerIndian commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +                </com.google.android.material.textfield.TextInputLayout>
добавил

2021-08-26 12:23 UTC, BikerIndian commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +                    android:layout_marginTop="86dp"
убрал

2021-08-26 12:23 UTC, BikerIndian commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +                </com.google.android.material.textfield.TextInputLayout>
добавил

2021-08-26 12:24 UTC, BikerIndian commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +                </com.google.android.material.textfield.TextInputLayout>
добавил

2021-08-26 12:24 UTC, BikerIndian commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +                    app:hintAnimationEnabled="false"
убрал

2021-08-26 12:24 UTC, BikerIndian commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +                    app:hintAnimationEnabled="false"
был для теста

2021-08-26 12:24 UTC, BikerIndian commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +                    android:layout_marginBottom="20dp"
указал

2021-08-26 12:25 UTC, BikerIndian commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +
сделал

2021-08-29 18:01 UTC, arsensaliev requested changes

2021-08-29 18:01 UTC, arsensaliev commented on feature-profile-edit/build.gradle
> +    implementation 'com.basgeekball:awesome-validation:4.3'
Нужно указать в Dependencies

2021-08-29 18:01 UTC, arsensaliev commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/main/ProfileEditFragment.kt
> +    private var mAwesomeValidation = AwesomeValidation(ValidationStyle.TEXT_INPUT_LAYOUT)
Переменную лучше назвать validator

2021-08-29 18:01 UTC, arsensaliev commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/main/ProfileEditFragment.kt
> +        viewModel.init()
viewModel должен инициализироваться в onViewCreated

2021-08-29 18:01 UTC, arsensaliev commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/main/ProfileEditViewModel.kt
> +    fun init() {
Если данный метод пустой, то лучше удалить

2021-08-29 18:01 UTC, arsensaliev commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/navigation/ProfileEditNavigator.kt
> +interface ProfileEditNavigator : BaseNavigator {
У вас вроде неправильно сделана навигация, спросите у Романа как должна быть.

2021-08-29 18:01 UTC, arsensaliev commented on feature-profile-edit/src/main/res/values/colors.xml
> +    <color name="button_save_color">#6550EE</color>
Данные цвета есть в core. Удалите этот файл.

2021-08-29 18:01 UTC, arsensaliev commented on feature-profile-edit/src/main/res/values/dimens.xml
> +    <dimen name="edit_text_layout_margin_start">20sp</dimen>
Должен быть вроде в dp. Так как в sp указываем размер текста.

2021-08-29 18:01 UTC, arsensaliev commented on feature-profile-edit/src/main/res/values/dimens.xml
> +    <dimen name="edit_text_layout_marginEnd">20sp</dimen>
Должен быть вроде в dp. Так как в sp указываем размер текста.

2021-08-29 18:01 UTC, arsensaliev commented on feature-profile-edit/src/main/res/values/dimens.xml
> +    <dimen name="edit_text_layout_height">85sp</dimen>
Должен быть вроде в dp. Так как в sp указываем размер текста.

2021-08-29 18:01 UTC, arsensaliev commented on feature-profile-edit/src/main/res/values/themes.xml
> +        <item name="android:textSize">12sp</item>
в dimens

2021-08-29 18:03 UTC, arsensaliev commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +                tools:ignore="UseAppTint" />
Да

2021-08-30 05:36 UTC, BikerIndian commented on feature-profile-edit/src/main/res/values/dimens.xml
> +    <dimen name="edit_text_layout_margin_start">20sp</dimen>
исправил

2021-08-30 05:40 UTC, BikerIndian commented on feature-profile-edit/src/main/res/values/colors.xml
> +    <color name="button_save_color">#6550EE</color>
удалил

2021-08-30 05:42 UTC, BikerIndian commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/main/ProfileEditFragment.kt
> +    private var mAwesomeValidation = AwesomeValidation(ValidationStyle.TEXT_INPUT_LAYOUT)
переименовал

2021-08-30 05:44 UTC, BikerIndian commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/main/ProfileEditFragment.kt
> +        viewModel.init()
эта часть кода из ProfileFragment

2021-08-30 05:44 UTC, BikerIndian commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/main/ProfileEditFragment.kt
> +        viewModel.init()
перенес

2021-08-30 05:47 UTC, BikerIndian commented on feature-profile-edit/build.gradle
> +    implementation 'com.basgeekball:awesome-validation:4.3'
Так на митинге договорились что этого не делаю.

2021-08-30 05:49 UTC, BikerIndian commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/main/ProfileEditViewModel.kt
> +    fun init() {
удалил

2021-08-30 05:55 UTC, BikerIndian commented on feature-profile-edit/src/main/res/values/dimens.xml
> +    <dimen name="edit_text_layout_marginEnd">20sp</dimen>
исправил

2021-08-30 05:57 UTC, BikerIndian commented on feature-profile-edit/src/main/res/values/dimens.xml
> +    <dimen name="edit_text_layout_height">85sp</dimen>
исправил

2021-08-30 06:03 UTC, BikerIndian commented on feature-profile-edit/src/main/res/values/themes.xml
> +        <item name="android:textSize">12sp</item>
перенес

2021-08-31 05:50 UTC, arsensaliev commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/view/ProfileEditFragment.kt
> +        return if (shouldShowError(editText)) {
ПОЖАЛУЙСТА не нажимайте кнопку resolve conversation. Это только должен делать reviewer!

2021-08-31 05:50 UTC, arsensaliev commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/view/ProfileEditFragment.kt
> +    private fun showErrorOff(editText: TextInputLayout) {
ПОЖАЛУЙСТА не нажимайте кнопку resolve conversation. Это только должен делать reviewer! У вас есть причина нажатия ?

2021-08-31 05:51 UTC, arsensaliev commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/view/ProfileEditFragment.kt
> +            val textLength = editText.text!!.length
ПОЖАЛУЙСТА не нажимайте кнопку resolve conversation. Это только должен делать reviewer! У вас есть причина нажатия ?

2021-08-31 06:05 UTC, BikerIndian commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/view/ProfileEditFragment.kt
> +        return if (shouldShowError(editText)) {
fixed: На митинге мне сказал что могу закрыть так как этот код убран.

2021-08-31 06:05 UTC, BikerIndian commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/view/ProfileEditFragment.kt
> +    private fun showErrorOff(editText: TextInputLayout) {
fixed: На митинге мне сказал что могу закрыть так как этот код убран.

2021-08-31 06:06 UTC, BikerIndian commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/view/ProfileEditFragment.kt
> +            val textLength = editText.text!!.length
fixed: На митинге мне сказал что могу закрыть так как этот код убран.

2021-08-31 06:07 UTC, BikerIndian commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/view/ProfileEditFragment.kt
> +        return false
fixed:  этот код удален.

2021-08-31 06:08 UTC, BikerIndian commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +
fixed

2021-08-31 06:11 UTC, BikerIndian commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +                </com.google.android.material.textfield.TextInputLayout>
fixed

2021-08-31 06:38 UTC, BikerIndian commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +        <androidx.cardview.widget.CardView
fixed

2021-08-31 06:40 UTC, BikerIndian commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +
fixed

2021-08-31 06:41 UTC, BikerIndian commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +                android:layout_width="91dp"
fixed

2021-08-31 06:41 UTC, BikerIndian commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +
fixed

2021-08-31 06:42 UTC, BikerIndian commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +
fixed

2021-08-31 07:02 UTC, arsensaliev commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/main/ProfileEditFragment.kt
> +
Лишние отступы.

2021-08-31 07:02 UTC, arsensaliev commented on feature-profile-edit/src/main/res/layout/fragment_profile_edit.xml
> +                tools:ignore="UseAppTint" />
Да

2021-08-31 12:57 UTC, BikerIndian commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/main/ProfileEditFragment.kt
> +
fixed

2021-09-01 06:29 UTC, arsensaliev approved these changes

2021-09-01 06:31 UTC, arsensaliev commented
Исправь конфликты

2021-09-01 15:28 UTC, merged