Implement Tours Repository
arsensaliev/demal-android pull request #20
Opened 2021-08-16 07:03 UTC by Koshake

Repository and data model for tours

2021-08-16 16:04 UTC, Romeo2005 requested changes
Ответь на вопросы и сделай enum

2021-08-16 16:04 UTC, RomchaDev commented on model/src/main/java/com/demal/model/data/entity/tours/Tour.kt
> +) : AppStateEntity
Зачем всюду добавлять SerializedName?

2021-08-16 16:04 UTC, RomchaDev commented on model/src/main/java/com/demal/model/data/entity/tours/Tours.kt
> +data class Tours(val toursList : List<Tour>) : AppStateEntity
Зачем этот класс?

2021-08-16 16:04 UTC, RomchaDev commented on repository/src/main/java/com/demal/repository/repository/ToursRepository.kt
> +    suspend fun getTourById(id: Int) : Tour
Думаю, стоит создать enum, для того, чтобы было понятно какие могут быть варианты для sortBy и для order. Я не уверен, где должно происходить преобразование из enum в string (Repository / DataSource). Погугли, то, что нагуглишь - мне брось, тоже почитаю.

2021-08-16 16:14 UTC, Koshake commented on model/src/main/java/com/demal/model/data/entity/tours/Tour.kt
> +) : AppStateEntity
Можно спокойно убрать, не особо это нужно

2021-08-16 16:20 UTC, Romeo2005 commented on model/src/main/java/com/demal/model/data/entity/tours/Tour.kt
> +) : AppStateEntity
Убери, если не нужно

2021-08-16 16:33 UTC, Koshake commented on model/src/main/java/com/demal/model/data/entity/tours/Tours.kt
> +data class Tours(val toursList : List<Tour>) : AppStateEntity
Как обертка над List<Tour>, ведь он не является AppStateEntity и я потом не смогу его передать в HomeViewModel. 
Сейчас вижу, что я в итоге нигде не использую класс Tours, а надо бы из функции getTours в ToursRepository возвращать тогда не List<Tour>, а Tours

2021-08-17 08:03 UTC, Koshake commented on repository/src/main/java/com/demal/repository/repository/ToursRepository.kt
> +    suspend fun getTourById(id: Int) : Tour
Нашла такую интересную статью
https://medium.com/tedpark-developer/how-to-use-enum-with-retrofit-query-path-d9c14b93d68f

2021-08-18 13:31 UTC, Romeo2005 commented on model/src/main/java/com/demal/model/data/entity/tours/Tours.kt
> +data class Tours(val toursList : List<Tour>) : AppStateEntity
Ты уже это сделала?

2021-08-18 13:32 UTC, Romeo2005 commented on repository/src/main/java/com/demal/repository/repository/ToursRepository.kt
> +    suspend fun getTourById(id: Int) : Tour
Отлично, надо реализовать

2021-08-19 06:26 UTC, Koshake commented on model/src/main/java/com/demal/model/data/entity/tours/Tour.kt
> +) : AppStateEntity
fixed

2021-08-19 06:26 UTC, Koshake commented on model/src/main/java/com/demal/model/data/entity/tours/Tours.kt
> +data class Tours(val toursList : List<Tour>) : AppStateEntity
fixed

2021-08-19 06:26 UTC, Koshake commented on repository/src/main/java/com/demal/repository/repository/ToursRepository.kt
> +    suspend fun getTourById(id: Int) : Tour
fixed

2021-08-19 10:24 UTC, Romeo2005 requested changes
Ещё немного вопросов. Ты проверяла работоспособность этого репозитория? Если нет, то нужно проверить

2021-08-19 10:24 UTC, Romeo2005 commented on model/src/main/java/com/demal/model/data/entity/tours/network/NetworkTour.kt
> +    val tour: TourResponse,
Наверное этот класс лучше назвать TourResponse, а тот, который сейчас так называетсся, назвать NetworkTour.

2021-08-19 10:24 UTC, Romeo2005 commented on model/src/main/java/com/demal/model/data/entity/tours/network/TourResponse.kt
> +    val id: Int,
Уже писал по поводу названий

2021-08-19 10:24 UTC, Romeo2005 commented on repository/src/main/java/com/demal/repository/types/EnumConverterFactory.kt
> +                } catch (exception: Exception) {
Насколько я понимаю, если у поля нету аннотации SerializedName, то этот метод вернёт null. Если это действительно так (я могу ошибаться), то это нужно исправить. Надо, чтобы если у поля небыло SerialisedName, этот метод возвращал название поля.

2021-08-19 11:18 UTC, Koshake commented on repository/src/main/java/com/demal/repository/types/EnumConverterFactory.kt
> +                } catch (exception: Exception) {
да, точно! ты прав. Мне тогда надо либо добавить SerializedName к каждому полю enum, либо переименовать поля c заглавных в строчные буквы. Как лучше сделать?

2021-08-19 13:15 UTC, Romeo2005 commented on repository/src/main/java/com/demal/repository/types/EnumConverterFactory.kt
> +                } catch (exception: Exception) {
Лучше добавить SerializedName. Аесли есть интерес и желание, то можно добавить в EnumConverterFactory поле namingPolicy и если туда передаётся значение CAMEL_CASE, то нужно преобразовать имя поля енама в camelCase. Но это совсем не обязательно.

2021-08-20 13:02 UTC, Koshake commented on model/src/main/java/com/demal/model/data/entity/tours/network/NetworkTour.kt
> +    val tour: TourResponse,
fixed

2021-08-20 13:02 UTC, Koshake commented on model/src/main/java/com/demal/model/data/entity/tours/network/TourResponse.kt
> +    val id: Int,
fixed

2021-08-20 13:03 UTC, Koshake commented on repository/src/main/java/com/demal/repository/types/EnumConverterFactory.kt
> +                } catch (exception: Exception) {
fixed

2021-08-20 13:26 UTC, Romeo2005 requested changes
Один небольшой вопрос по структуре папок

2021-08-20 13:26 UTC, Romeo2005 commented on model/src/main/java/com/demal/model/data/entity/tours/network/NetworkTour.kt
> -    val tour: TourResponse,
Он уже не "Network", нужно переименовать. Для юзера я вообще не создавал отдельного пакета network, что, возможно, не хорошо. Но в network должны лежать только классы request и response. Tour нужно убрать из этого пакета.

2021-08-20 13:30 UTC, Koshake commented on model/src/main/java/com/demal/model/data/entity/tours/network/NetworkTour.kt
> -    val tour: TourResponse,
Сама сомневаюсь как нейминг сделать. Теперь переименовать NetworkTour в TourResponse, а TourResponse в просто Tour?

2021-08-20 13:34 UTC, Romeo2005 commented on model/src/main/java/com/demal/model/data/entity/tours/network/NetworkTour.kt
> -    val tour: TourResponse,
NetworkTour в Tour

2021-08-20 13:46 UTC, Koshake commented on model/src/main/java/com/demal/model/data/entity/tours/network/NetworkTour.kt
> -    val tour: TourResponse,
fixed

2021-08-24 09:35 UTC, Romeo2005 requested changes
Resolve conversations

2021-08-24 09:35 UTC, Romeo2005 commented on repository/src/main/java/com/demal/repository/repository/UserRepositoryImpl.kt
> +    private val responseRepository: UserRepositoryLocal,
Rename to userRepositoryLocal

2021-08-24 09:35 UTC, Romeo2005 commented on model/src/main/java/com/demal/model/data/entity/tours/ITour.kt
> +    val id: Int
Make some fields not nullable

2021-08-24 09:49 UTC, merged