Implement Image Working
arsensaliev/demal-android pull request #21
Opened 2021-08-16 11:29 UTC by Romeo2005

2021-08-16 16:15 UTC, Romeo2005 reviewed
Да вроде бы всё ок

2021-08-17 05:05 UTC, arsensaliev requested changes

2021-08-17 05:05 UTC, arsensaliev commented on repository/src/main/java/com/demal/repository/image/GlideImageLoader.kt
> +        loadingCode: Int?,
В чём цель LoadingCode ?

2021-08-17 05:05 UTC, arsensaliev commented on repository/src/main/java/com/demal/repository/image/ImageLoader.kt
> +interface ImageLoader<T> {
На Generic лучше сделать более жесткую связь и брать наследников от View.

2021-08-17 08:53 UTC, Romeo2005 commented on repository/src/main/java/com/demal/repository/image/GlideImageLoader.kt
> +        loadingCode: Int?,
Может быть полезно, если надо будет с использованием одного loader и одного listener загрузить разные изображения в разные контейнеры

2021-08-17 09:18 UTC, Romeo2005 commented on repository/src/main/java/com/demal/repository/image/ImageLoader.kt
> +interface ImageLoader<T> {
Этот интерфейс не должен знать о андроид классах. Иначе потеряется смысл создания интерфейсов

2021-08-18 10:56 UTC, arsensaliev approved these changes

2021-08-18 10:56 UTC, merged