Feature: fragment my tours
arsensaliev/demal-android pull request #22
Opened 2021-08-16 18:43 UTC by NikKonshin

Creare custom view and laid out fragment_my_tours

2021-08-17 11:02 UTC, arsensaliev commented
Ветка названа неправильно, в именах веток вместо _ должно быть дефис. Например feature/my-tour была бы лучше. Слово fragment ничего не значит в данном случае.

2021-08-18 10:08 UTC, arsensaliev requested changes

2021-08-18 10:08 UTC, arsensaliev commented on feature-mytours/build.gradle
> +    id 'com.android.application'
Модуль должен был создаться с помощью com.android.library. Почему у тебя так ? В Android Studio показывает что модуль mytours является отдельным приложением без активити.

2021-08-18 10:13 UTC, arsensaliev requested changes

2021-08-18 10:13 UTC, arsensaliev commented on feature-mytours/src/main/res/values/colors.xml
> +    <color name="black">#FF000000</color>
Все эти цвета вроде уже есть в core модуле. Используй оттуда, не надо пересоздавать одни и те же цвета.

2021-08-19 11:07 UTC, NikKonshin commented on feature-mytours/src/main/res/values/colors.xml
> +    <color name="black">#FF000000</color>
Поправил

2021-08-19 11:07 UTC, NikKonshin commented on feature-mytours/build.gradle
> +    id 'com.android.application'
Поправил

2021-08-19 13:25 UTC, Romeo2005 commented
В названии ПР каждое слово должно начинаться с заглавной буквы

2021-08-19 13:53 UTC, Romeo2005 requested changes
Есть пару вопросов

2021-08-19 13:53 UTC, Romeo2005 commented on feature-mytours/src/main/java/com/demal/view/MyToursFragment.kt
> +
В таком случае, для инициализации фрагмента достаточно 
`class MyToursFragment : Fragment(R.layout.fragment_my_tours) `. OnCreateView не нужен. Создание ViewModel и добавление на экран логики будет вынесено в отдельный ПР?

2021-08-19 13:53 UTC, Romeo2005 commented on feature-mytours/src/main/res/values-night/themes.xml
> +</resources>
Удали пакет values-night со всем содержимым

2021-08-19 13:53 UTC, Romeo2005 commented on feature-mytours/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
Зачем hello_blank_fragment and app_name?

2021-08-19 13:53 UTC, Romeo2005 commented on feature-mytours/src/main/java/com/demal/view/ActiveInactiveView.kt
> +        val action = event?.action
Тут студия почему-то ругается

2021-08-20 11:45 UTC, NikKonshin commented on feature-mytours/src/main/java/com/demal/view/MyToursFragment.kt
> +
fixed

2021-08-20 11:45 UTC, NikKonshin commented on feature-mytours/src/main/res/values-night/themes.xml
> +</resources>
fixed

2021-08-20 11:45 UTC, NikKonshin commented on feature-mytours/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
fixed

2021-08-20 11:46 UTC, NikKonshin commented on feature-mytours/src/main/java/com/demal/view/ActiveInactiveView.kt
> +        val action = event?.action
Этот метод нужен для того, чтобы слабовидящие могли пользоваться, нам нужно сейчас это реализовывать?

2021-08-20 11:47 UTC, NikKonshin commented on feature-mytours/src/main/java/com/demal/view/ActiveInactiveView.kt
> +        val action = event?.action
Точнее студия предлагает добавить этот метод.

2021-08-20 12:49 UTC, Romeo2005 commented on feature-mytours/src/main/java/com/demal/view/ActiveInactiveView.kt
> +        val action = event?.action
А, да нет, пусть будет как есть

2021-08-20 14:09 UTC, Romeo2005 approved these changes

2021-08-22 10:35 UTC, arsensaliev commented
В файл settings.gradle забыли подключить модуль. Также в папке buildSrc есть файл Dependencies.kt. Там подключите свой модуль и добавьте его в файл graddle в модуле app.

2021-08-24 13:08 UTC, merged