Implement Login Layout
arsensaliev/demal-android pull request #24
Opened 2021-08-27 13:59 UTC by AlinaDorozhkina

2021-08-27 15:57 UTC, arsensaliev requested changes
Вы сделали замечательную работу, но стоит сделать небольшой рефактор по стилю кода. Как всё исправите напишите мне в телегу. Так же нужно ответить на вопросы который я задал в PR. Отвечать на вопросы надо именно в PR так как переписка должна быть доступна всем. Если что-ли исправили напишите под комментарием fixed. Еще одно замечание. У вас картинка некачественная и стоит без затемнения. Если возникнут проблемы с этим, можете мне написать помогу. Еще надо добавить скрытие и показ пароля с иконкой глаза.

2021-08-27 15:57 UTC, arsensaliev commented on buildSrc/src/main/java/Dependencies.kt
> +    const val kotlinVersion = "1.5.0"
Зачем поменяли версию kotlin ?

2021-08-27 15:57 UTC, arsensaliev commented on buildSrc/src/main/java/Dependencies.kt
> +    const val valid = "com.basgeekball:awesome-validation:${Versions.validation}"
Лучше назвать переменную validator или validation

2021-08-27 15:57 UTC, arsensaliev commented on core/src/main/res/values/dimens.xml
> +    <dimen name="margin_login_top_bottom">213dp</dimen>
Не надо указывать margin. Лучше сделать constarint по центру вертикально и горизонтально.

2021-08-27 15:57 UTC, arsensaliev commented on feature-login/src/main/java/com/demal/feature_login/main/LoginFragment.kt
> +        bindingNullable?.let {
Надо обращаться на binding. В BaseFragment есть переменная binding, она не может быть nullebale. Удобно, теперь необязательно ставить проверку через let.

2021-08-27 15:57 UTC, arsensaliev commented on feature-login/src/main/java/com/demal/feature_login/main/LoginFragment.kt
> +    private val mAwesomeValidation = AwesomeValidation(ValidationStyle.TEXT_INPUT_LAYOUT)
лучше назвать validator

2021-08-27 15:57 UTC, arsensaliev commented on feature-login/src/main/java/com/demal/feature_login/main/LoginFragment.kt
> +                if (mAwesomeValidation.validate()) {
Для чего это проверка которая ничего не делает ?

2021-08-27 15:57 UTC, arsensaliev commented on feature-login/src/main/java/com/demal/feature_login/main/LoginFragment.kt
> +
Лишний отступ.

2021-08-27 15:57 UTC, arsensaliev commented on feature-login/src/main/java/com/demal/feature_login/main/LoginFragment.kt
> +            mAwesomeValidation.addValidation(
Добавление всех валидации лучше хранить в отдельном методе чтобы не засорять onViewCreated.

2021-08-27 15:57 UTC, arsensaliev commented on feature-login/src/main/res/layout/fragment_login.xml
> +    android:background="@drawable/auth_background_image">
Задний фон не выглядит так как в Figma. Там она затемнением, также качество лучше. Почему-то в верстке у вас плохое качество.

2021-08-27 15:57 UTC, arsensaliev commented on feature-login/src/main/res/layout/fragment_login.xml
> +        android:layout_marginBottom="@dimen/margin_login_top_bottom"
MarginTop и MarginBottom бесполезны, так как constraintLayout и так без них центрирует по вертикали. Что на счёт MarginStart и marginEnd то их тоже надо удалить и указать их в constraint по бокам по 20dp

2021-08-27 15:57 UTC, arsensaliev commented on feature-login/src/main/res/layout/fragment_login.xml
> +            android:layout_marginTop="20dp"
В dimens

2021-08-27 15:57 UTC, arsensaliev commented on model/src/main/java/com/demal/model/data/entity/login/LoginStatus.kt
> +    val isSuccessed: Boolean
Что означает это ?

2021-08-28 12:47 UTC, AlinaDorozhkina commented on buildSrc/src/main/java/Dependencies.kt
> +    const val kotlinVersion = "1.5.0"
fixed

2021-08-28 12:47 UTC, AlinaDorozhkina commented on buildSrc/src/main/java/Dependencies.kt
> +    const val valid = "com.basgeekball:awesome-validation:${Versions.validation}"
fixed

2021-08-28 12:55 UTC, AlinaDorozhkina commented on feature-login/src/main/java/com/demal/feature_login/main/LoginFragment.kt
> +        bindingNullable?.let {
fixed

2021-08-28 12:57 UTC, AlinaDorozhkina commented on feature-login/src/main/java/com/demal/feature_login/main/LoginFragment.kt
> +            mAwesomeValidation.addValidation(
fixed

2021-08-28 12:57 UTC, AlinaDorozhkina commented on feature-login/src/main/res/layout/fragment_login.xml
> +    android:background="@drawable/auth_background_image">
fixed
заменила картинку фона (экспорт из фигмы)

2021-08-28 12:59 UTC, AlinaDorozhkina commented on model/src/main/java/com/demal/model/data/entity/login/LoginStatus.kt
> +    val isSuccessed: Boolean
на будущее, проверка будет, есть ли пользователь с введенными данными

2021-08-28 13:19 UTC, AlinaDorozhkina commented on feature-login/src/main/res/layout/fragment_login.xml
> +            android:layout_marginTop="20dp"
fixed

2021-08-28 13:20 UTC, AlinaDorozhkina commented on feature-login/src/main/res/layout/fragment_login.xml
> +        android:layout_marginBottom="@dimen/margin_login_top_bottom"
вот этот момент не поняла - как указать по бокам без marginStart и marginEnd?

2021-08-28 13:20 UTC, AlinaDorozhkina commented on feature-login/src/main/java/com/demal/feature_login/main/LoginFragment.kt
> +    private val mAwesomeValidation = AwesomeValidation(ValidationStyle.TEXT_INPUT_LAYOUT)
fixed

2021-08-28 13:21 UTC, AlinaDorozhkina commented on core/src/main/res/values/dimens.xml
> +    <dimen name="margin_login_top_bottom">213dp</dimen>
fixed

2021-09-01 15:25 UTC, arsensaliev approved these changes
Исправьте конфликты.

2021-09-01 17:12 UTC, AlinaDorozhkina commented
исправила

  
>Среда, 1 сентября 2021, 18:25 +03:00 от Arsen ***@***.***>:
> 
> 
***@***.*** approved this pull request.
>Исправьте конфликты.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .  
 
 
--
Алина Дорожкина
 

2021-09-02 14:17 UTC, arsensaliev approved these changes

2021-09-02 14:18 UTC, merged