Implement Wishlist Screen
arsensaliev/demal-android pull request #26
Opened 2021-08-30 14:23 UTC by Dentag

Implemented Wishlist Screen

2021-08-31 11:37 UTC, Romeo2005 requested changes
Есть несколько замечаний

2021-08-31 11:37 UTC, Romeo2005 commented on core/src/main/java/com/demal/view/core/adapter/BaseAdapter.kt
> +    private val imageLoader: ImageLoader<ImageView>
Неправильно передавать imageLoader в BaseAdapter, так как он не всюду нужен. Также предлагаю сделать listener nullable.

2021-08-31 11:37 UTC, Romeo2005 commented on core/src/main/java/com/demal/view/core/adapter/BaseAdapter.kt
> +        fun bind(data: T, listener: L, imageLoader: ImageLoader<ImageView>) =
Нельзя в него imageLoader передавать

2021-08-31 11:37 UTC, Romeo2005 commented on core/src/main/java/com/demal/view/core/adapter/Bindings.kt
> +val tourBind: ((View, LikableTour, TourClickListener, ImageLoader<ImageView>) -> Unit) =
Можно его сделать, как расширение для интерфейса ToursListWorkerFragment, либо ImageWorkerFragment, в котором будет обязательное поле imageLoader.

2021-08-31 11:37 UTC, Romeo2005 commented on feature-wishlist/src/main/java/com/demal/feature_wishlist/main/WishlistFragment.kt
> +        GlideImageLoader()
Уже есть imageModule

2021-08-31 11:37 UTC, Romeo2005 commented on feature-wishlist/src/main/java/com/demal/feature_wishlist/main/WishlistFragment.kt
> +        if (tourAdapter == null) {
Так он же по любому null на момент вызова этого метода. Зачем условие? Да и если оно нужно, то лучше какой-то let использовать

2021-08-31 11:37 UTC, Romeo2005 commented on feature-wishlist/src/main/java/com/demal/feature_wishlist/main/WishlistFragment.kt
> +            renderMessage("onItem click")
Нужно сделать имитацию перехода на экран тура с вызовом метода навигатора из вью модели. Потом просто в навигатор функционал добавится и всё заработает

2021-08-31 11:53 UTC, Dentag commented on feature-wishlist/src/main/java/com/demal/feature_wishlist/main/WishlistFragment.kt
> +        if (tourAdapter == null) {
Если не ошибаюсь - фрагмент может хранитсья в памяти в каких-то случаях, соответственно адаптер может быть уже инициализирован и заново это делать нет необходимости. Через let оформляется когда он не null, нас интересует только если он null.

2021-09-02 08:15 UTC, Dentag commented on core/src/main/java/com/demal/view/core/adapter/BaseAdapter.kt
> +    private val imageLoader: ImageLoader<ImageView>
fixed

2021-09-02 08:15 UTC, Dentag commented on core/src/main/java/com/demal/view/core/adapter/BaseAdapter.kt
> +        fun bind(data: T, listener: L, imageLoader: ImageLoader<ImageView>) =
fixed

2021-09-02 08:15 UTC, Dentag commented on core/src/main/java/com/demal/view/core/adapter/Bindings.kt
> +val tourBind: ((View, LikableTour, TourClickListener, ImageLoader<ImageView>) -> Unit) =
fixed

2021-09-02 08:15 UTC, Dentag commented on feature-wishlist/src/main/java/com/demal/feature_wishlist/main/WishlistFragment.kt
> +        GlideImageLoader()
fixed

2021-09-02 08:16 UTC, Dentag commented on feature-wishlist/src/main/java/com/demal/feature_wishlist/main/WishlistFragment.kt
> +            renderMessage("onItem click")
fixed

2021-09-02 14:01 UTC, Romeo2005 approved these changes

2021-09-02 14:40 UTC, arsensaliev requested changes

2021-09-02 14:40 UTC, arsensaliev commented on feature-wishlist/build.gradle
> +    implementation Koin.koinViewModel
Нужно подключить Koin.koinCore

2021-09-02 14:42 UTC, Dentag commented on feature-wishlist/build.gradle
> +    implementation Koin.koinViewModel
fixed

2021-09-02 14:46 UTC, arsensaliev approved these changes

2021-09-02 14:46 UTC, merged