Implement Profile Edit  Layout
arsensaliev/demal-android pull request #32
Opened 2021-09-03 10:28 UTC by BikerIndian

2021-09-10 18:39 UTC, Romeo2005 requested changes
Несколько замечаний

2021-09-10 18:39 UTC, RomchaDev commented on app/src/main/java/com/demal/main/MainViewModel.kt
> +    }
В MainViewModel инициализируютсься только методы для навигации через BottomNavigation.

2021-09-10 18:39 UTC, RomchaDev commented on app/src/main/java/com/demal/navigation/MainBottomNavigation.kt
> +    fun toProfileEditScreen()
Разве можно попасть на ProfileEdit через BottomNavigation? Если нет, то тут этого метода быть не должно

2021-09-10 18:39 UTC, RomchaDev commented on app/src/main/java/com/demal/navigation/Navigator.kt
> +    override fun toBack() = router.exit()
"toBack" звучит как-то не по английски. Назови его просто "back", или "toPrevious"

2021-09-10 18:39 UTC, RomchaDev commented on core/src/main/java/com/demal/view/core/BaseNavigator.kt
> +    fun toBack()
Писал про название метода

2021-09-10 18:39 UTC, RomchaDev commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/main/ProfileEditFragment.kt
> +    private val FILE_TYPE = "image/*"
Почему его не вынести в companion object, в виде константы?

2021-09-10 18:39 UTC, RomchaDev commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/main/ProfileEditFragment.kt
> +        setSelectPhotoListener()
Думаю, одного раза достаточно

2021-09-10 18:39 UTC, RomchaDev commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/main/ProfileEditFragment.kt
> +        viewModel.updateAvatar(uriPhoto,context)
Используй автоформат

2021-09-10 18:39 UTC, RomchaDev commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/main/ProfileEditViewModel.kt
> +        }
Нужно создать класс FileGetter, инджектить его во viewModel и грузить картинки через него

2021-09-10 18:39 UTC, RomchaDev commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/navigation/ProfileEditNavigator.kt
> +    fun toProfileScreen()
Где он используется?

2021-09-10 18:39 UTC, RomchaDev commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/main/ProfileEditViewModel.kt
> +    val navigator: ProfileEditNavigator,
Если используется только метод toBack(), то можно передавать BaseNavigator, a не ProfileEditNavigator

2021-09-10 18:39 UTC, Romeo2005 commented on repository/src/main/java/com/demal/repository/data_sources/RemoteDataSourceImpl.kt
> +            val body = MultipartBody.Part.createFormData("image", "image.jpg", requestFile)
Не думаю, что этому коду здесь место. Может лучше прямо в классе FileGetter это делать?

2021-09-13 12:08 UTC, BikerIndian commented on app/src/main/java/com/demal/navigation/Navigator.kt
> +    override fun toBack() = router.exit()
исправил

2021-09-13 12:08 UTC, BikerIndian commented on core/src/main/java/com/demal/view/core/BaseNavigator.kt
> +    fun toBack()
исправил

2021-09-13 12:11 UTC, BikerIndian commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/main/ProfileEditFragment.kt
> +    private val FILE_TYPE = "image/*"
вынес

2021-09-13 12:12 UTC, BikerIndian commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/main/ProfileEditFragment.kt
> +        viewModel.updateAvatar(uriPhoto,context)
сделано

2021-09-13 12:15 UTC, BikerIndian commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/navigation/ProfileEditNavigator.kt
> +    fun toProfileScreen()
убрал

2021-09-13 12:17 UTC, BikerIndian commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/main/ProfileEditViewModel.kt
> +    val navigator: ProfileEditNavigator,
поменял

2021-09-13 12:42 UTC, BikerIndian commented on repository/src/main/java/com/demal/repository/data_sources/RemoteDataSourceImpl.kt
> +            val body = MultipartBody.Part.createFormData("image", "image.jpg", requestFile)
в данном случае используется okhttp3.MultipartBody и выносить её за пределы репозитория в другие методы и потом тащить её через интерфейсы, не лучшая идея. А с ByteArray таких проблем нет.

2021-09-15 11:24 UTC, BikerIndian commented on app/src/main/java/com/demal/main/MainViewModel.kt
> +    }
убрал

2021-09-15 11:48 UTC, BikerIndian commented on app/src/main/java/com/demal/navigation/MainBottomNavigation.kt
> +    fun toProfileEditScreen()
убрал

2021-09-17 05:10 UTC, Romeo2005 commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/main/ProfileEditViewModel.kt
> +    val navigator: ProfileEditNavigator,
Тогода удали ProfileEditNavigator и из koin тоже его удали

2021-09-17 05:11 UTC, Romeo2005 commented on feature-profile-edit/src/main/java/com/demal/feature_profile_edit/main/ProfileEditViewModel.kt
> +        }
Просто сделай инджект ContentFileUtil через koin

2021-09-21 21:01 UTC, Romeo2005 approved these changes

2021-09-21 21:34 UTC, merged