Feature: Create ViewModel And Added screen My Tours Functionality
arsensaliev/demal-android pull request #34
Opened 2021-09-04 10:10 UTC by NikKonshin

2021-09-05 04:48 UTC, arsensaliev requested changes
PR назван неправильно. Нужно исправить комментарий и ответить на некоторые.

2021-09-05 04:48 UTC, arsensaliev commented on feature-mytours/src/main/java/com/demal/view/MyToursFragment.kt
> +
Лишние отступы, также отформатируй все твой файлы.

2021-09-05 04:48 UTC, arsensaliev commented on feature-mytours/src/main/java/com/demal/view/MyToursFragment.kt
> +    private fun showTextIsEmpty(){
Добавь отступ перед каждым методом

2021-09-05 04:48 UTC, arsensaliev commented on feature-mytours/src/main/java/com/demal/view_model/MyToursViewModel.kt
> +    private var mState: Boolean = false
Непонятно что значит это переменная. Назови понятным образом. И вообще зачем это переменная нужна ?

2021-09-05 04:48 UTC, arsensaliev commented on feature-mytours/src/main/java/com/demal/view_model/MyToursViewModel.kt
> +//          чтобы он зависил от state
Непонятный комментарий. Что имелось ввиду ?

2021-09-05 04:48 UTC, arsensaliev commented on feature-mytours/src/main/java/com/demal/view_model/MyToursViewModel.kt
> +    private suspend fun setLiveData(state: Boolean) {
Зачем разделил метод на setLiveData и getTours ? Это немного путает код. Также лучше не делать вложенные параметры которые делают какое либо логику. Ещё аргумент state не используется в этом методе, бесполезный параметр значит. Посмотри вариант Дениса: 
![image](https://user-images.githubusercontent.com/52528182/132115514-ee83cbc6-1d2f-48c8-a999-065d9722047f.png)

2021-09-05 04:48 UTC, arsensaliev commented on feature-mytours/src/main/java/com/demal/view_model/MyToursViewModel.kt
> +    fun onItemClick(tour: LikableTour) {}
Добавь метод перехода на экран тура и передай tourId. Пример есть в wishlist.

2021-09-05 04:48 UTC, arsensaliev commented on feature-mytours/src/main/res/layout/fragment_my_tours.xml
> +    <com.google.android.material.progressindicator.CircularProgressIndicator
Добавь отступы перед каждый новым View.

2021-09-05 14:59 UTC, NikKonshin commented on feature-mytours/src/main/java/com/demal/view_model/MyToursViewModel.kt
> +//          чтобы он зависил от state
Думал, что отображение прошедших дат, зависит от сервера.
Напишу логику.

2021-09-05 15:04 UTC, NikKonshin commented on feature-mytours/src/main/java/com/demal/view_model/MyToursViewModel.kt
> +    private suspend fun setLiveData(state: Boolean) {
В данном случае, state это состояние кнопки, от которого будет зависить отображение активных туров и прошедших. Можно конечно это разделить на 2 метода во вьюмодели, наверно так и сделаю. getTours это публичный метод, поскольку запрос данных нужен и в других методах вьюмодели сделал метод который запускает получение данных отдельно. У Дениса немного другая задача.

2021-09-05 15:11 UTC, NikKonshin commented on feature-mytours/src/main/java/com/demal/view/MyToursFragment.kt
> +
Торопился сдать перед митингом(

2021-09-05 18:55 UTC, NikKonshin commented on feature-mytours/src/main/java/com/demal/view/MyToursFragment.kt
> +
fixed

2021-09-05 18:55 UTC, NikKonshin commented on feature-mytours/src/main/java/com/demal/view/MyToursFragment.kt
> +    private fun showTextIsEmpty(){
fixed

2021-09-05 18:55 UTC, NikKonshin commented on feature-mytours/src/main/java/com/demal/view_model/MyToursViewModel.kt
> +    private var mState: Boolean = false
Реализовал иначе

2021-09-05 18:55 UTC, NikKonshin commented on feature-mytours/src/main/java/com/demal/view_model/MyToursViewModel.kt
> +//          чтобы он зависил от state
fixed

2021-09-05 18:58 UTC, NikKonshin commented on feature-mytours/src/main/java/com/demal/view_model/MyToursViewModel.kt
> +    private suspend fun setLiveData(state: Boolean) {
fixed

2021-09-05 18:59 UTC, NikKonshin commented on feature-mytours/src/main/java/com/demal/view_model/MyToursViewModel.kt
> +    fun onItemClick(tour: LikableTour) {}
fixed

2021-09-05 18:59 UTC, NikKonshin commented on feature-mytours/src/main/res/layout/fragment_my_tours.xml
> +    <com.google.android.material.progressindicator.CircularProgressIndicator
fixed

2021-09-08 06:20 UTC, arsensaliev requested changes

2021-09-08 06:20 UTC, arsensaliev commented on core/src/main/java/com/demal/view/core/adapter/Bindings.kt
> +        val date = "$dayTour $monthTour $yearTour"
Лучше создать метод который уже возвращает готовое значение.

2021-09-08 06:20 UTC, arsensaliev commented on feature-mytours/src/main/java/com/demal/view/MyToursFragment.kt
> +        }
Надо добавить ещё скрытие загрузки в else hideLoading()

2021-09-08 06:20 UTC, arsensaliev commented on feature-mytours/src/main/java/com/demal/view_model/MyToursViewModel.kt
> +            val inactiveTours = LikableTours(tours.toursList.filter { !dateUtill.statusTour(it.startDate) })
getActiveTour и getInactiveTour очень похожи. Можно оптимизировать эти методы и не повторяться кодом. Допустим ты сначала можешь получить туры а потом их сортировать.

2021-09-08 06:32 UTC, merged

2021-09-08 16:28 UTC, NikKonshin commented on core/src/main/java/com/demal/view/core/adapter/Bindings.kt
> +        val date = "$dayTour $monthTour $yearTour"
fixed

2021-09-08 16:36 UTC, NikKonshin commented on feature-mytours/src/main/java/com/demal/view/MyToursFragment.kt
> +        }
fixed

2021-09-08 16:42 UTC, NikKonshin commented on feature-mytours/src/main/java/com/demal/view_model/MyToursViewModel.kt
> +            val inactiveTours = LikableTours(tours.toursList.filter { !dateUtill.statusTour(it.startDate) })
Проблема в том, что для того чтобы получать актуальную информацию, необходимо получать туры каждый раз при нажатии на кнопку активные неактивные, до того момента, пока не будет нормально работать локальное хранение данных.