Implement Getting Tours On Home Screen
arsensaliev/demal-android pull request #35
Opened 2021-09-05 06:50 UTC by Koshake

Getting and showing tours on home screen.
Fragment, viewModel, adapter implemented

2021-09-05 10:24 UTC, arsensaliev requested changes
Размеры не соответствует по фигме. Карточки item не соответствует как в фигме. Также следует добавить затемнение фотографии. Стоит пересмотреть все размеры и указать как в figma. В Item для картинок используется у вас ImageView а надо по хорошому ShapeableImageView. Посмотрите вариант универсального макета item_tour.xml в core.  И да если не добавить чуть затемнение картинки то белый текст плохо будет виден.

2021-09-05 10:24 UTC, arsensaliev commented on feature-home/src/main/res/layout/fragment_home.xml
> +        style="@style/ItemMainTextView"
Размеры не соответствует как в фигме. У тебя 18sp в Фигме 20sp.

2021-09-05 10:24 UTC, arsensaliev commented on feature-home/src/main/res/layout/fragment_home.xml
>          android:layout_height="0dp"
200dp в фигме.

2021-09-05 10:24 UTC, arsensaliev commented on feature-home/src/main/res/layout/fragment_home.xml
>          android:layout_height="wrap_content"
200dp

2021-09-05 10:24 UTC, arsensaliev commented on feature-home/src/main/res/layout/fragment_home.xml
>          android:layout_height="0dp"
Размеры не соответствует по фигме. RecyclerView не должен быть выше 200dp. Стоит пересмотреть все размеры и указать как в figma.

2021-09-05 10:24 UTC, arsensaliev commented on feature-home/src/main/res/layout/fragment_home.xml
>          android:layout_height="0dp"
Размеры не соответствует по фигме. RecyclerView не должен быть выше 200dp. Стоит пересмотреть все размеры и указать как в figma.

2021-09-06 09:09 UTC, Koshake commented on feature-home/src/main/res/layout/fragment_home.xml
> +        style="@style/ItemMainTextView"
fixed

2021-09-06 09:09 UTC, Koshake commented on feature-home/src/main/res/layout/fragment_home.xml
>          android:layout_height="0dp"
fixed

2021-09-06 09:10 UTC, Koshake commented on feature-home/src/main/res/layout/fragment_home.xml
>          android:layout_height="wrap_content"
fixed

2021-09-06 09:10 UTC, Koshake commented on feature-home/src/main/res/layout/fragment_home.xml
>          android:layout_height="0dp"
fixed

2021-09-06 09:10 UTC, Koshake commented on feature-home/src/main/res/layout/fragment_home.xml
>          android:layout_height="0dp"
fixed

2021-09-07 08:45 UTC, arsensaliev approved these changes

2021-09-07 08:45 UTC, merged