Implement Login Verification
arsensaliev/demal-android pull request #38
Opened 2021-09-09 13:01 UTC by AlinaDorozhkina

2021-09-10 10:30 UTC, arsensaliev requested changes

2021-09-10 10:30 UTC, arsensaliev commented on feature-login/src/main/java/com/demal/feature_login/main/LoginFragment.kt
> +    private val emailValidator = AwesomeValidation(ValidationStyle.TEXT_INPUT_LAYOUT)
Зачем создавать 2 инстанса одного и того же объекта ? Помню ранее был 1 валидатор.

2021-09-10 10:30 UTC, arsensaliev commented on feature-login/src/main/java/com/demal/feature_login/main/LoginFragment.kt
> +        initPasswordValidation()
3 метода лишние. Можно было создать 1 метод который добавляет все валидации. Назвать его addInputValidations() и всё три метода добавлении валидации вызывать из этого метода. Тем самым у нас будет красивый и чистый onViewCreated!

2021-09-10 10:30 UTC, arsensaliev commented on feature-login/src/main/java/com/demal/feature_login/main/LoginViewModel.kt
> +    private var status = LoginStatus(true)
Зачем нужен эта переменная ?

2021-09-15 07:03 UTC, AlinaDorozhkina commented on feature-login/src/main/java/com/demal/feature_login/main/LoginFragment.kt
> +    private val emailValidator = AwesomeValidation(ValidationStyle.TEXT_INPUT_LAYOUT)
Это не один и тот же объект . Один отвечает за валидацию емайла, второй - пароля .
Сделала это для того , чтобы проверка полей происходила не по нажатию войти, а когда поле в фокусе и пользователь сразу видит , правильно ли он вводит данные . С точки зрения UX это корректное  поведение (в идеале , конечно, когда фокус потерян , выводить ошибку - это надо докрутить . )
А когда у меня один объект , то обе проверки я на него вешаю . И нужного поведения не получу никогда .

2021-09-15 07:08 UTC, AlinaDorozhkina commented on feature-login/src/main/java/com/demal/feature_login/main/LoginFragment.kt
> +        initPasswordValidation()
Тогда будет один огромный метод со всем подряд, исходя из моей идеи , которую я выше озвучила . Нас учили разбивать код на мелкие задачи и методы

2021-09-15 07:09 UTC, AlinaDorozhkina commented on feature-login/src/main/java/com/demal/feature_login/main/LoginViewModel.kt
> +    private var status = LoginStatus(true)
Да не к чему . Думаю из app state entity удалить переменную вообще и будет пустой класс . 
По сути мне и не нужна эта entity я так понимаю

2021-09-16 09:05 UTC, arsensaliev commented on feature-login/src/main/java/com/demal/feature_login/main/LoginFragment.kt
> +        initPasswordValidation()
Надо создать метод init в котором вызывается остальные методы. Таким образом наш onViewCreated метод будет чистым.

2021-09-16 09:17 UTC, arsensaliev commented on feature-login/src/main/java/com/demal/feature_login/main/LoginViewModel.kt
> +    private var status = LoginStatus(true)
Тогда стоит переделать.

2021-09-17 13:46 UTC, AlinaDorozhkina commented on feature-login/src/main/java/com/demal/feature_login/main/LoginViewModel.kt
> +    private var status = LoginStatus(true)
когда пользователь существует , то вызывается  у фрагмента  метод  renderSuccess(state.data), соответственно в него надо передать что-то.  Что мне передавать ? По сути не надо же ничего. Если функция логин не кинула ошибку, то успешно и пользователь существует.
Но  я не могу отказаться от переменной в своем AppStateEntity по этой причине, и потому что дата класс требует какую-то проперти в конструктор. 
Я выбрала булевую переменную и когда SUCCESS , кидаю true.

2021-09-17 13:46 UTC, AlinaDorozhkina commented on feature-login/src/main/java/com/demal/feature_login/main/LoginViewModel.kt
> +    private var status = LoginStatus(true)
Я избавилась от этой переменной  таким образом: в своей app state entity LoginStatus переменной isSuccessed присвоила сразу значение true. И если функция логин не кинула ошибку, то я делаю так mStateLiveData.postValue(BaseState.Success(LoginStatus()))

2021-09-17 13:46 UTC, AlinaDorozhkina commented on feature-login/src/main/java/com/demal/feature_login/main/LoginViewModel.kt
> +    private var status = LoginStatus(true)
но еще не запушила

2021-09-17 13:47 UTC, AlinaDorozhkina commented on feature-login/src/main/java/com/demal/feature_login/main/LoginFragment.kt
> +        initPasswordValidation()
fixed

2021-09-18 16:48 UTC, AlinaDorozhkina commented on feature-login/src/main/java/com/demal/feature_login/main/LoginViewModel.kt
> +    private var status = LoginStatus(true)
fixed

2021-09-20 03:29 UTC, arsensaliev approved these changes

2021-09-20 03:30 UTC, merged