Implement New Home Screen Structure
arsensaliev/demal-android pull request #40
Opened 2021-09-13 09:09 UTC by Koshake

Feature: fragment for home tours
Feature: fragment for categories
Feature: getting categories from server

2021-09-13 21:40 UTC, Romeo2005 requested changes
Есть вопросы

2021-09-13 21:40 UTC, RomchaDev commented on feature-home/src/main/java/com/demal/feature_home/main/view/HomeCategoriesFragment.kt
> +
Почему этот метод пустой? Даже если нужная логика пока отсутствует, лучше сразу передать нажатие во вью модель и потом добавить её туда.

2021-09-13 21:40 UTC, Romeo2005 commented on feature-home/src/main/java/com/demal/feature_home/main/view_model/HomeCategoriesViewModel.kt
> +
Почему бы тут не вызвать метод toToursScreen у навигатора?

2021-09-13 21:40 UTC, Romeo2005 commented on feature-home/src/main/res/layout/fragment_home.xml
> +        <fragment
Студия говорит, что нужно заменить fragment на FragmentContainerView

2021-09-13 21:40 UTC, Romeo2005 commented on feature-home/src/main/res/layout/fragment_home_categories.xml
> +        android:id="@+id/activiries_info_textview"
Ошибка в слове "activities"

2021-09-13 21:40 UTC, Romeo2005 commented on model/src/main/java/com/demal/model/data/entity/category/Category.kt
>          return this.id == other.id
Для этого созданы аннотации.

2021-09-13 21:40 UTC, Romeo2005 commented on model/src/main/java/com/demal/model/data/entity/category/Category.kt
> +data class Category(private val category: CategoryResponse) : ICategory by category,
Зачем разделять Category и CategoryResponse на разные классы. Всё поля ведь у них одинаковые, а для работы со списком можно использовать аннотации, а не переопределять методы DiffUtil.

2021-09-13 21:40 UTC, Romeo2005 commented on model/src/main/java/com/demal/model/data/entity/category/Category.kt
>  import com.demal.model.data.entity.tours.network.CategoryResponse
CategoryResponse не должен лежать в пакете entity.tours

2021-09-14 09:26 UTC, Koshake commented on feature-home/src/main/java/com/demal/feature_home/main/view/HomeCategoriesFragment.kt
> +
fixed

2021-09-14 09:26 UTC, Koshake commented on feature-home/src/main/java/com/demal/feature_home/main/view_model/HomeCategoriesViewModel.kt
> +
fixed

2021-09-14 09:26 UTC, Koshake commented on feature-home/src/main/res/layout/fragment_home.xml
> +        <fragment
fixed

2021-09-14 09:26 UTC, Koshake commented on feature-home/src/main/res/layout/fragment_home_categories.xml
> +        android:id="@+id/activiries_info_textview"
fixed

2021-09-14 09:26 UTC, Koshake commented on model/src/main/java/com/demal/model/data/entity/category/Category.kt
>          return this.id == other.id
fixed

2021-09-14 09:26 UTC, Koshake commented on model/src/main/java/com/demal/model/data/entity/category/Category.kt
> +data class Category(private val category: CategoryResponse) : ICategory by category,
fixed

2021-09-14 09:26 UTC, Koshake commented on model/src/main/java/com/demal/model/data/entity/category/Category.kt
>  import com.demal.model.data.entity.tours.network.CategoryResponse
fixed

2021-09-14 15:53 UTC, Romeo2005 reviewed
Ещё 2 коммента

2021-09-14 15:53 UTC, Romeo2005 commented on model/src/main/java/com/demal/model/data/entity/category/CategoryResponse.kt
> +data class CategoryResponse(
Мне кажется, что лучше этот клас назвать просто Category

2021-09-14 15:53 UTC, Romeo2005 commented on model/src/main/java/com/demal/model/data/entity/tours/network/CategoryResponse.kt
> -package com.demal.model.data.entity.tours.network
Удали этот пустой файл

2021-09-15 06:13 UTC, Koshake commented on model/src/main/java/com/demal/model/data/entity/tours/network/CategoryResponse.kt
> -package com.demal.model.data.entity.tours.network
fixed

2021-09-15 06:13 UTC, Koshake commented on model/src/main/java/com/demal/model/data/entity/category/CategoryResponse.kt
> +data class CategoryResponse(
fixed

2021-09-15 14:23 UTC, arsensaliev approved these changes

2021-09-15 14:25 UTC, merged