Feature/network authorization api
arsensaliev/demal-android pull request #7
Opened 2021-08-07 11:00 UTC by BikerIndian

2021-08-07 11:06 UTC, arsensaliev commented
Ты в неправильную ветку направил PR на master. master ветка эта ветка где мы делаем production версию. Измени слияние на dev ветку.

2021-08-07 11:11 UTC, arsensaliev commented
PR назван неправильно. Надо соблюдать правила именования PR.  
Implement - добавлена фича
Fix - исправлен баг или ошибка
Refactor - оптимизирован код или перемещение файлов.
Допустим твой PR может называться вот так. Implement Network Authentication

2021-08-09 05:59 UTC, arsensaliev requested changes
Вы не создали класс AppState для слежения удачного запроса на сервер

2021-08-09 06:49 UTC, BikerIndian commented
> AppState

2021-08-09 10:17 UTC, arsensaliev requested changes
Реализуйте сохранение токена в shared preferences. Поищите информацию в интернете, как работать с shared preferences в многомодульном приложении. Надо также добавить обработчик 401 ошибки. Если сервер выдаст 401 ошибку, то надо удалять старый токен. Потому срок действии токена может истечь.

2021-08-09 10:17 UTC, arsensaliev commented on app/src/main/java/com/demal/MainActivity.kt
> +    private fun authResult(auth: AuthenticationResultDto) {
MainActivity не должен у нас делать запросы на сервер. Она должна быть почти пустая, кроме навигации ничего там не должно быть!

2021-08-09 10:17 UTC, arsensaliev commented on app/src/main/java/com/demal/MainActivity.kt
> +    fun handleError(error: Throwable) {
У нас должен быть BaseFragment файл в котором есть метод renderDataкоторый делает всю эту работу обработки Success, Loading, Error запросов на сервер неудачный.

2021-08-09 10:17 UTC, arsensaliev commented on model/src/main/java/com/demal/model/dto/auth/Auth.kt
> +package com.demal.model.dto.auth
Распределение папок указана неправильно. Должно быть так: model -> data -> user-> entity

2021-08-09 10:17 UTC, arsensaliev commented on model/src/main/java/com/demal/model/dto/auth/AuthenticationResultDto.kt
> +class AuthenticationResultDto(
Это класс не должен называть Dto, так как Dto называется те классы которые конвертируются с помощью GSON. Достаточно назвать AuthResult. Также этот класс должен быть data class, так как это entity.

2021-08-09 10:17 UTC, arsensaliev commented on app/src/main/java/com/demal/MainActivity.kt
> +import com.demal.repository.Repository
Классы репозитория и иные другие модули касающиеся бизнес логики не должны быть в MainActivity

2021-08-09 10:17 UTC, arsensaliev commented on app/src/main/java/com/demal/MainActivity.kt
> +        var repository: Repository = RetrofitImplementation()
У нас должен быть DI с помощью Koin, на данный момент Рома уже подключает Koin. Сделай merge ветки Ромы себе. Ветка Ромы называется: feature/nagivation-koin.

2021-08-09 10:17 UTC, arsensaliev commented on model/src/main/java/com/demal/model/dto/auth/Auth.kt
> +class Auth {
Этот класс должен быть data class, потому это entity

2021-08-09 10:17 UTC, arsensaliev commented on model/src/main/java/com/demal/model/dto/auth/AuthenticationServerDto.kt
> +class AuthenticationServerDto(
Класс должен называться AuthDto. Длинные именование классов плохая практика.

2021-08-09 10:17 UTC, arsensaliev commented on model/src/main/java/com/demal/model/dto/auth/AuthenticationServerDto.kt
> +    @field:SerializedName("password") val pass: String?
Важные переменные лучше не сокращать, так как не понятно что значит pass. Назови переменное полным именем password.

2021-08-09 10:17 UTC, arsensaliev commented on model/src/main/java/com/demal/model/dto/auth/User.kt
> +class User {
Этот класс должен быть data class

2021-08-09 10:17 UTC, arsensaliev commented on repository/src/main/java/com/demal/repository/Repository.kt
> +    suspend fun getAuthData(login: String,pass: String): AuthenticationResultDto
Метод лучше назвать прямым контекстом "login". Также надо всегда использовать форматирование кода.

2021-08-09 10:17 UTC, arsensaliev commented on repository/src/main/java/com/demal/repository/RetrofitImplementation.kt
> +    override suspend fun getAuthData(email: String,pass: String): AuthenticationResultDto {
Метод будет называть login, так как мы поменяли в интерфейсе название метода. Также выходят warnings, надо исправить!

2021-08-09 10:17 UTC, arsensaliev commented on repository/src/main/java/com/demal/repository/RetrofitImplementation.kt
> +    private fun createRetrofit(interceptor: Interceptor): Retrofit {
Создание инстанса Retrofit должен быть в Koin. В модуле app в файле KoinModules должно происходит примерно так.
![image](https://user-images.githubusercontent.com/52528182/128689488-1bc97f3a-fa8d-413e-a851-b134eae7a13b.png)

2021-08-09 10:17 UTC, arsensaliev commented on repository/src/main/java/com/demal/repository/RetrofitImplementation.kt
> +    private fun createOkHttpClient(interceptor: Interceptor): OkHttpClient {
Этот метод тоже должен быть в koin

2021-08-09 10:17 UTC, arsensaliev commented on repository/src/main/java/com/demal/repository/RetrofitImplementation.kt
> +        private const val BASE_URL_LOCATIONS = "https://demal-api.herokuapp.com/api/v1/"
Нельзя в коде указывать URL сервера, для этого есть build.properties.

2021-08-09 10:17 UTC, arsensaliev commented on repository/src/main/java/com/demal/repository/api/ApiService.kt
> +    fun getAuthData(@Body auth : AuthenticationServerDto): Deferred<AuthenticationResultDto>
метод должен называться login

2021-08-09 10:33 UTC, arsensaliev commented
Нужно исправить конфликты

2021-08-12 20:28 UTC, Romeo2005 requested changes
Исправить замечания

2021-08-12 20:28 UTC, Romeo2005 commented on app/src/main/java/com/demal/koin/modules/KoinModules.kt
> +}
Разбить на разные файлы

2021-08-12 20:28 UTC, Romeo2005 commented on app/src/main/java/com/demal/main/MainActivity.kt
>  import org.koin.android.viewmodel.ext.android.viewModel
Удалить Snackbar dependency

2021-08-12 20:28 UTC, Romeo2005 commented on feature-profile/build.gradle
>  }
Импортировать model модуль через Modules

2021-08-12 20:28 UTC, Romeo2005 commented on repository/src/main/java/com/demal/repository/api/BaseInterceptor.kt
> +
Удалить ненужный комментарий

2021-08-12 20:39 UTC, Romeo2005 commented on app/src/main/java/com/demal/koin/modules/KoinModules.kt
> +}
Fixed

2021-08-12 20:46 UTC, Romeo2005 commented on app/src/main/java/com/demal/main/MainActivity.kt
>  import org.koin.android.viewmodel.ext.android.viewModel
Fixed

2021-08-12 20:46 UTC, Romeo2005 commented on feature-profile/build.gradle
>  }
Fixed

2021-08-12 20:46 UTC, Romeo2005 commented on repository/src/main/java/com/demal/repository/api/BaseInterceptor.kt
> +
Fixed

2021-08-12 20:57 UTC, Romeo2005 approved these changes

2021-08-14 15:17 UTC, Romeo2005 requested changes

2021-08-14 15:17 UTC, Romeo2005 commented on app/src/main/java/com/demal/koin/modules/NavigationModules.kt
>  }
Drop to NavigationModules and ViewModelModules

2021-08-14 15:20 UTC, Romeo2005 commented on app/src/main/java/com/demal/koin/modules/NavigationModules.kt
>  }
fixed

2021-08-14 15:22 UTC, Romeo2005 approved these changes

2021-08-15 06:07 UTC, arsensaliev requested changes

2021-08-15 06:07 UTC, arsensaliev commented on app/build.gradle
> +    implementation Retrofit.logging_interceptor
Все переменные graddle должны быть в стиле camelCase

2021-08-15 06:07 UTC, arsensaliev commented on app/src/main/java/com/demal/koin/modules/ApiModules.kt
> +const val BASE_URL_LOCATIONS = "https://demal-api.herokuapp.com/api/v1/"
base url должен быть без приставок api/v1. Так как у нас есть путь к получение фоток.
https://demal-api.herokuapp.com/uploads/d5ee3e1f-20fa-4394-b271-13a2acb8efa5.jpg
Выше это путь к аватарке. Там нет приставок api/v1. 
Думаю лучше BaseUrl сделать так: https://demal-api.herokuapp.com/ или если есть метод где можно два раза объявить или переопределять url отдельно для получение картинок то можно воспользоваться этим.

2021-08-15 06:07 UTC, arsensaliev commented on app/src/main/java/com/demal/navigation/Navigator.kt
> +) : MainActivityNavigator, BaseNavigator, ProfileNavigator {
Думаю по правильности наследовании первый должен быть BaseNavigator а потом другие. Важно соблюдать  иерархию.

2021-08-15 06:07 UTC, arsensaliev commented on core/src/main/java/com/demal/view/core/view/BaseFragment.kt
> +    protected val binding get() = bindingNullable!!
Что делает этот код ? Если bindingNullable будет null то приложение упадёт ?

2021-08-15 06:07 UTC, arsensaliev commented on core/src/main/java/com/demal/view/core/view/BaseFragment.kt
> +        viewModel.stateLiveData.observe(this) { state ->
Лучше подписывать в OnViewCreated. Об этом написано здесь: https://stackoverflow.com/questions/65426428/is-it-safe-to-observe-livedata-inside-onactivitycreated-or-onviewcreated

2021-08-15 06:07 UTC, arsensaliev commented on core/src/main/java/com/demal/view/core/view_model/BaseViewModel.kt
> +    @CallSuper
Зачем эта аннотация ?

2021-08-15 06:07 UTC, arsensaliev commented on feature-profile/src/main/java/com/demal/feature_profile/main/ProfileFragment.kt
> +    BaseFragment<FragmentProfileBinding, User, ProfileViewModel>() {
Я тут подумал, вспомнил экран Tours. Где надо делать 2 запроса. Первый на получение CategoryEntity и второй на TourEntity. Как это будет работать здесь ?
![Tours](https://user-images.githubusercontent.com/52528182/129468283-26cc4856-7f3c-4c22-84c7-e17a88e58634.png)

2021-08-15 06:07 UTC, arsensaliev commented on feature-profile/src/main/java/com/demal/feature_profile/main/ProfileFragment.kt
> +        binding.profileLocation.text = data.email
Сейчас приходит с сервера.

2021-08-15 08:48 UTC, Romeo2005 commented on core/src/main/java/com/demal/view/core/view_model/BaseViewModel.kt
> +    @CallSuper
Перенаправление на экран логина при 401 ошибке - это базовая логика, которая не должна иметь возможность быть измененной наследниками. Поэтому при переопределении метода handleError() нужно обязательно вызывать super.handleError(), о чём данная аннотация и говорит.

2021-08-15 08:51 UTC, Romeo2005 commented on app/build.gradle
> +    implementation Retrofit.logging_interceptor
Fixed

2021-08-15 08:53 UTC, Romeo2005 commented on app/src/main/java/com/demal/koin/modules/ApiModules.kt
> +const val BASE_URL_LOCATIONS = "https://demal-api.herokuapp.com/api/v1/"
Fixed

2021-08-15 08:55 UTC, Romeo2005 commented on app/src/main/java/com/demal/navigation/Navigator.kt
> +) : MainActivityNavigator, BaseNavigator, ProfileNavigator {
Fixed

2021-08-15 09:03 UTC, Romeo2005 commented on core/src/main/java/com/demal/view/core/view/BaseFragment.kt
> +    protected val binding get() = bindingNullable!!
Binding обязательно нужно занулять, когда он уже не нужен (в onDestroyView), иначе возникнут утечки памяти, так как он будет хранить ссылку на ненужную вью. Поэтому создается пара binding и в onDestroyView bindingNullable зануляется. not null binding создан для того, чтоб не заморачиваться с null-safety там, где это на самом деле не нужно. Мы ведь знаем, что bindingNullable равен null только после onDestroyView, а тогда он уже и не нужен никому. Это не я придумал, вроде би на поплибах было

2021-08-15 09:08 UTC, Romeo2005 commented on core/src/main/java/com/demal/view/core/view/BaseFragment.kt
> +        viewModel.stateLiveData.observe(this) { state ->
Fixed

2021-08-15 09:11 UTC, Romeo2005 commented on feature-profile/src/main/java/com/demal/feature_profile/main/ProfileFragment.kt
> +    BaseFragment<FragmentProfileBinding, User, ProfileViewModel>() {
Создадим класс ToursViewState, где будет присутствовать список категорий и список туров. И в Success будем передавать его.

2021-08-15 09:29 UTC, arsensaliev requested changes

2021-08-15 09:29 UTC, arsensaliev commented on repository/src/main/java/com/demal/repository/api/ApiService.kt
> +    @POST("api/v1/users/login")
что постоянно не повторять длинное значение api/v1 создай константу API_V1 и используй так "$API_V1/users/login". Не знаю куда будешь объявлять константу, но можешь в этом же файле сделать.

2021-08-15 09:32 UTC, Romeo2005 commented on feature-profile/src/main/java/com/demal/feature_profile/main/ProfileFragment.kt
> +        binding.profileLocation.text = data.email
Fixed

2021-08-15 09:35 UTC, arsensaliev commented on repository/src/main/java/com/demal/repository/api/ApiService.kt
> +    @POST("api/v1/users/login")
Это ещё является best practies

2021-08-15 09:36 UTC, Romeo2005 commented on repository/src/main/java/com/demal/repository/api/ApiService.kt
> +    @POST("api/v1/users/login")
Fixed

2021-08-15 09:56 UTC, arsensaliev requested changes

2021-08-15 09:56 UTC, arsensaliev commented on model/src/main/java/com/demal/model/data/entity/user/User.kt
> +    val city: String,
![image](https://user-images.githubusercontent.com/52528182/129474515-329e4274-1100-46ce-a411-0f0fa7770810.png)
Некоторые поля могут быть null. В данном случае у нас могут null быть country и city.

2021-08-15 10:34 UTC, Romeo2005 commented on model/src/main/java/com/demal/model/data/entity/user/User.kt
> +    val city: String,
Fixed

2021-08-15 10:36 UTC, arsensaliev requested changes

2021-08-15 10:36 UTC, arsensaliev commented on model/src/main/java/com/demal/model/data/entity/user/User.kt
> +    val country: String?,
Наверное было бы легче сделать так `val country: String? = ""`. Тогда тот код с условиями вряд-ли понадобится

2021-08-15 15:38 UTC, merged