Feature/Home
arsensaliev/demal-android pull request #8
Opened 2021-08-08 18:22 UTC by Koshake

2021-08-09 12:22 UTC, arsensaliev commented
Надо исправить конфликты

2021-08-09 14:54 UTC, Romeo2005 commented
PR назван неправильно. Надо соблюдать правила именования PR.
Implement - добавлена фича
Fix - исправлен баг или ошибка
Refactor - оптимизирован код или перемещение файлов.
Допустим твой PR может называться вот так. Implement Home Layout

2021-08-09 15:56 UTC, Romeo2005 requested changes
Исправьте замечания и напишите fixed в ответ на них. Вынесите это в отдельный модуль и назовите его "feat_home"

2021-08-09 15:56 UTC, Romeo2005 commented on app/src/main/res/values/colors.xml
> +    <color name="purple_light_10">#1A6550EE</color>
Непонятно, что значит "_10". Лучше назвать purple_light_variant

2021-08-09 15:56 UTC, Romeo2005 commented on app/src/main/res/layout/item_home_activities.xml
> +    xmlns:tool="http://schemas.android.com/tools"
Лучше назвать файл home_item_category

2021-08-09 15:56 UTC, Romeo2005 commented on app/src/main/res/layout/item_home.xml
> +    xmlns:app="http://schemas.android.com/apk/res-auto"
Лучше назвать файл home_item_tour

2021-08-09 15:57 UTC, Romeo2005 commented
Вынесите это в отдельный модуль и назовите его "feat_home"

2021-08-10 09:51 UTC, Koshake commented on app/src/main/res/values/colors.xml
> +    <color name="purple_light_10">#1A6550EE</color>
fixed

2021-08-10 09:51 UTC, Koshake commented on app/src/main/res/layout/item_home_activities.xml
> +    xmlns:tool="http://schemas.android.com/tools"
fixed

2021-08-10 09:51 UTC, Koshake commented on app/src/main/res/layout/item_home.xml
> +    xmlns:app="http://schemas.android.com/apk/res-auto"
fixed

2021-08-10 11:45 UTC, RomchaDev commented on app/src/main/res/layout/item_home.xml
> +            app:srcCompat="@drawable/home_card_image" />
Добавьте следующую строку в ImageView: android:scaleType="centerCrop", иначе возникает проблема, которая показана на картинке: 
![itemProblem](https://user-images.githubusercontent.com/67197145/128746913-a8eb5333-bc0a-43c3-be0c-14ff6f518156.PNG) Также проблема связанна с тем, что item_home_width у вас 160dp, что не совпадает с размером изображения. Сделай примерно 130.

2021-08-10 11:45 UTC, RomchaDev commented on app/src/main/res/values/dimens.xml
> +    <dimen name="item_home_width">160dp</dimen>
item_home_with  сделай 130dp

2021-08-10 12:01 UTC, Koshake commented on app/src/main/res/values/dimens.xml
> +    <dimen name="item_home_width">160dp</dimen>
fixed

2021-08-10 12:01 UTC, Koshake commented on app/src/main/res/layout/item_home.xml
> +            app:srcCompat="@drawable/home_card_image" />
fixed

2021-08-11 15:31 UTC, Romeo2005 requested changes
Нужно исправить новые замечания

2021-08-11 15:31 UTC, RomchaDev commented on feat_home/src/androidTest/java/com/demal/feat_home/ExampleInstrumentedTest.kt
> +
Удаляйте файлы с примерами тестов. Думаю, мы и сами сможем тесты написать)

2021-08-11 15:31 UTC, RomchaDev commented on feat_home/src/main/AndroidManifest.xml
> +</manifest>
Удали namespace, он не нужен. Прислушивайся к подсказкам студии

2021-08-11 15:31 UTC, Romeo2005 commented on feature-home/build.gradle
> +
Убери блок android

2021-08-11 15:31 UTC, RomchaDev commented on feature-home/src/androidTest/java/com/demal/feature-home/ExampleInstrumentedTest.kt
> +import androidx.test.ext.junit.runners.AndroidJUnit4
feature-home - это название модуля, а пакеты надо называть через snake_case. То есть в твоём случае пакет должен называться "feature_home".  В манифесте тоже не забудь поменять, иначе работать не будет.

1. Ставишь курсор на `feature-home` , нажимаешь shift+F6 и меняешь название на "feature_home"
2. В манифесте своего модуля меняешь название пакета на "feature_home"

2021-08-11 15:31 UTC, RomchaDev commented on feature-home/src/main/AndroidManifest.xml
> +</manifest>
Уже писал по поводу названия пакета

2021-08-11 15:31 UTC, RomchaDev commented on feature-home/src/androidTest/java/com/demal/feature-home/ExampleInstrumentedTest.kt
> +    }
Удаляй файлы с примерами тестов. Я думаю, мы и сами тесты написать сможем)

2021-08-11 15:31 UTC, Romeo2005 commented on feature-home/src/test/java/com/demal/feature-home/ExampleUnitTest.kt
> + *
Удаляй файлы с примерами тестов. Я думаю, мы и сами тесты написать сможем)

2021-08-11 15:38 UTC, Romeo2005 commented
Конфликт исправить надо. Если не выйдет - пиши. Также, после того как исправишь конфликт, надо будет использовать ресурсы из core модуля, а ненужные ресурсы из своего модуля надо будет удалить

2021-08-12 15:16 UTC, Koshake commented on feature-home/src/androidTest/java/com/demal/feature-home/ExampleInstrumentedTest.kt
> +    }
fixed

2021-08-12 15:16 UTC, Koshake commented on feature-home/src/main/AndroidManifest.xml
> +</manifest>
fixed

2021-08-12 15:16 UTC, Koshake commented on feature-home/src/androidTest/java/com/demal/feature-home/ExampleInstrumentedTest.kt
> +import androidx.test.ext.junit.runners.AndroidJUnit4
fixed

2021-08-12 15:16 UTC, Koshake commented on feature-home/build.gradle
> +
fixed

2021-08-12 15:16 UTC, Koshake commented on feat_home/src/main/AndroidManifest.xml
> +</manifest>
fixed

2021-08-12 15:16 UTC, Koshake commented on feat_home/src/androidTest/java/com/demal/feat_home/ExampleInstrumentedTest.kt
> +
fixed

2021-08-12 18:54 UTC, Romeo2005 approved these changes

2021-08-12 18:55 UTC, merged